-- Disposable migrated database only. Everything, including test helpers, rolls back.
begin;
select no_plan();
create function pg_temp.org(n integer default 1) returns uuid language sql as $$select ('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.project(n integer default 1) returns uuid language sql as $$select ('c0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.person(n integer) returns uuid language sql as $$select ('a0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.doc() returns uuid language sql as $$select 'd0000000-0000-4000-8000-000000000001'::uuid$$;
create function pg_temp.req() returns uuid language sql as $$select current_setting('test.request')::uuid$$;
create function pg_temp.request_date(days integer default 5) returns uuid language sql as $$select public.request_submission_date_change(pg_temp.org(),pg_temp.project(),pg_temp.doc(),current_date+days,'Waiting for coordinated vendor information')$$;
create function pg_temp.review(decision text default 'approve',number text default null) returns text language sql as $$select public.review_deliverable_request(pg_temp.org(),pg_temp.project(),pg_temp.req(),decision,'Reviewed against the project plan',number)$$;
create function pg_temp.add_request() returns uuid language sql as $$select public.request_additional_deliverable(pg_temp.org(),pg_temp.project(),'New pump assessment','Special Inspection Register','Mechanical',current_date+10,'Additional scope identified during design')$$;
insert into auth.users(id,email) select pg_temp.person(n),'request-'||n||'@example.test' from generate_series(1,6)n;
insert into public.profiles(id,display_name,email_snapshot) select id,'Request Tester',email from auth.users where email like 'request-%@example.test';
insert into public.organisations(id,slug,name,created_by) values(pg_temp.org(),'request-a','Request A',pg_temp.person(1)),(pg_temp.org(2),'request-b','Request B',pg_temp.person(5));
insert into public.organisation_memberships(organisation_id,user_id,role)
 select pg_temp.org(case when n=5 then 2 else 1 end),pg_temp.person(n),case when n=4 then 'organisation_admin' else 'member' end::public.organisation_role from generate_series(1,6)n;
insert into public.projects(id,organisation_id,code,name,created_by,revision_cycle_days)
 values(pg_temp.project(),pg_temp.org(),'REQUEST-A','Request A',pg_temp.person(1),3),(pg_temp.project(2),pg_temp.org(2),'REQUEST-B','Request B',pg_temp.person(5),3);
insert into public.project_memberships(organisation_id,project_id,user_id,role)
 select pg_temp.org(case when n=5 then 2 else 1 end),pg_temp.project(case when n=5 then 2 else 1 end),pg_temp.person(n),
 case when n in (1,5) then 'project_admin' when n=2 then 'document_controller' else 'engineer' end::public.project_role from generate_series(1,6)n;
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
insert into public.document_categories(organisation_id,kind,code,name) values(pg_temp.org(),'discipline','MEC','Mechanical');
insert into public.project_member_disciplines(organisation_id,project_id,user_id,discipline)
 select pg_temp.org(),pg_temp.project(),pg_temp.person(n),'Mechanical' from unnest(array[3,6])n;
insert into public.documents(id,organisation_id,project_id,document_number,title,document_type,discipline,planned_submission_date)
 values(pg_temp.doc(),pg_temp.org(),pg_temp.project(),'MEC-001','Existing pump drawing','Drawing','Mechanical',current_date-2);
insert into public.document_assignments(organisation_id,project_id,document_id,user_id) values(pg_temp.org(),pg_temp.project(),pg_temp.doc(),pg_temp.person(3));
select ok(not has_table_privilege('authenticated','public.deliverable_requests','INSERT'),'browser cannot directly create requests');
select ok(not has_table_privilege('authenticated','public.deliverable_requests','UPDATE'),'browser cannot bypass approvals');
select ok(not has_table_privilege('authenticated','public.deliverable_requests','DELETE'),'request history cannot be deleted by browser');
select ok(not has_function_privilege('anon','public.request_submission_date_change(uuid,uuid,uuid,date,text)','EXECUTE'),'anonymous date requests denied');
select ok(not has_function_privilege('anon','public.review_deliverable_request(uuid,uuid,uuid,text,text,text)','EXECUTE'),'anonymous reviews denied');
select ok(not has_function_privilege('authenticated','public.deliverable_request_engineer_authorised(uuid,uuid,uuid,text,uuid)','EXECUTE'),'arbitrary member authorisation helper is private');
select ok((select relrowsecurity from pg_class where oid='public.deliverable_requests'::regclass),'request table has RLS');
select ok(position('''deliverable_requests''' in pg_get_functiondef('public.read_project_member_preview(uuid,text,jsonb)'::regprocedure))>0,'read-only member preview includes requests');

select set_config('request.jwt.claim.sub',pg_temp.person(6)::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.request_date()$$,'42501',null,'unassigned engineer cannot request a document date change');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.request_date(-1)$$,'22023',null,'past requested date denied');
select throws_ok($$select public.request_submission_date_change(pg_temp.org(),pg_temp.project(),pg_temp.doc(),current_date+5,'')$$,'22023',null,'reason required');
select set_config('test.request',pg_temp.request_date()::text,true);
select is((select status from public.deliverable_requests where id=pg_temp.req()),'pending_pm','engineer request starts with PM');
select is((select due_date from public.document_submission_deadline(pg_temp.doc())),current_date-2,'request alone does not change date');
select throws_ok($$select pg_temp.request_date(7)$$,'23505',null,'only one active date request per document');
select throws_ok($$select pg_temp.review()$$,'42501',null,'engineer cannot approve own request');
reset role;
select is((select count(*)::integer from public.notifications where kind='deliverable_request_pending_pm'),2,'PM and requester notified');
select is((select count(*)::integer from public.notification_email_deliveries),2,'notifications enqueue email');
select ok((select bool_and(href like '%/requests?request=%') from public.notifications),'notification links address the exact request');

select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.review()$$,'42501',null,'DCC cannot accept before PM');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(4)::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.review()$$,'42501',null,'organisation administrator cannot replace PM/DCC');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(5)::text,true);
set local role authenticated;
select is((select count(*)::integer from public.deliverable_requests),0,'foreign tenant cannot read requests');
select throws_ok($$select pg_temp.review()$$,'42501',null,'foreign tenant cannot review requests');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(6)::text,true);
set local role authenticated;
select is((select count(*)::integer from public.deliverable_requests),0,'another engineer cannot read pending requests');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(1)::text,true);
set local role authenticated;
select is(pg_temp.review(),'pending_dcc','PM approval sends to DCC');
select is((select due_date from public.document_submission_deadline(pg_temp.doc())),current_date-2,'PM approval does not yet change date');
select throws_ok($$select pg_temp.review()$$,'42501',null,'PM cannot perform the second approval');
reset role;
select is((select count(*)::integer from public.notifications where kind='deliverable_request_pending_dcc' and recipient_user_id=pg_temp.person(2)),1,'DCC notified after PM approval');
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
set local role authenticated;
select is(pg_temp.review(),'accepted','DCC completes date approval');
select is((select due_date from public.document_submission_deadline(pg_temp.doc())),current_date+5,'accepted date drives the live deadline');
select is((select deadline_kind from public.document_submission_deadline(pg_temp.doc())),'approved_change','approved date is identified in MDR');
select is((select overdue from public.document_submission_deadline(pg_temp.doc())),false,'approved future date closes current overdue state');
select is((select planned_submission_date from public.documents where id=pg_temp.doc()),current_date-2,'original baseline is preserved');
select is((select next_submission_date from public.project_document_progress where document_id=pg_temp.doc()),current_date+5,'MDR progress view follows approval');
select throws_ok($$select pg_temp.review()$$,'22023',null,'double acceptance rejected');
reset role;
select is((select count(*)::integer from public.audit_events where target_id=pg_temp.req()),3,'submission and both decisions audited');
select is((select due_date from public.document_submission_deadline(pg_temp.doc(),current_date-1)),current_date-2,'historical cutoff does not see future approval');
select set_config('request.jwt.claim.sub',pg_temp.person(6)::text,true);
set local role authenticated;
select is((select due_date from public.document_submission_deadline(pg_temp.doc())),current_date+5,'other authorised readers see the same approved deadline');
reset role;

-- Receipt of a newer revision invalidates only the old deadline override.
insert into public.document_revisions(id,organisation_id,project_id,document_id,revision_code,issue_status,issue_date,state,original_filename,declared_mime,byte_size,sha256,storage_key,uploaded_by)
 values('e0000000-0000-4000-8000-000000000001',pg_temp.org(),pg_temp.project(),pg_temp.doc(),'A','Issued for Review (IFR)',current_date,'pending_upload','test.pdf','application/pdf',10,repeat('a',64),'request-test/a',pg_temp.person(3));
select is((select due_date from public.document_submission_deadline(pg_temp.doc())),current_date+5,'incomplete upload retains approved deadline');
update public.document_revisions set state='quarantined' where document_id=pg_temp.doc();
select is((select due_date from public.document_submission_deadline(pg_temp.doc())),public.add_project_working_days(current_date,3),'new receipt resumes agreed revision cycle');

select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
set local role authenticated;
select set_config('test.request',pg_temp.request_date(20)::text,true);
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(1)::text,true);
set local role authenticated;
select is(pg_temp.review(),'pending_dcc','next revision date can be requested');
reset role;
update public.document_revisions set issue_date=current_date-1 where document_id=pg_temp.doc();
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
set local role authenticated;
select is(pg_temp.review(),'superseded','changed issue/deadline cannot get stale DCC approval');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
set local role authenticated;
select set_config('test.request',pg_temp.request_date(21)::text,true);
select lives_ok($$select public.cancel_deliverable_request(pg_temp.org(),pg_temp.project(),pg_temp.req())$$,'requester can cancel pending date change');
select is((select status from public.deliverable_requests where id=pg_temp.req()),'cancelled','cancellation retained in history');
select set_config('test.request',pg_temp.request_date(22)::text,true);
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(1)::text,true);
set local role authenticated;
select throws_ok($$select public.review_deliverable_request(pg_temp.org(),pg_temp.project(),pg_temp.req(),'reject','')$$,'22023',null,'rejection requires reason');
select is(pg_temp.review('reject'),'rejected','PM can reject request');
reset role;

-- DCC approval of additional scope uses the same unique MDR index and assignment RPC.
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
set local role authenticated;
select throws_ok($$select public.request_additional_deliverable(pg_temp.org(),pg_temp.project(),'Unscoped drawing','Drawing','Electrical',current_date+10,'Additional electrical scope')$$,'42501',null,'engineer cannot add unauthorised discipline');
select set_config('test.request',pg_temp.add_request()::text,true);
select is((select status from public.deliverable_requests where id=pg_temp.req()),'pending_dcc','additional deliverable goes directly to DCC');
select throws_ok($$select pg_temp.add_request()$$,'23505',null,'retry cannot create identical pending scope requests');
reset role;
select is((select count(*)::integer from public.documents),1,'no document created before approval');
select set_config('request.jwt.claim.sub',pg_temp.person(1)::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.review('approve','MEC-002')$$,'42501',null,'PM cannot approve additional deliverable in place of DCC');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.review()$$,'22023',null,'DCC must assign a document number');
select throws_ok($$select pg_temp.review('approve','  mec-001 ')$$,'23505',null,'duplicate number rejected case-insensitively after trimming');
select is((select status from public.deliverable_requests where id=pg_temp.req()),'pending_dcc','number collision leaves request pending');
select is((select count(*)::integer from public.documents),1,'collision leaves MDR unchanged');
select is(pg_temp.review('approve','MEC-002'),'accepted','DCC can approve using a unique number');
reset role;
select is((select document_type from public.documents where document_number='MEC-002'),'Special Inspection Register','free document types retained');
select is((select planned_submission_date from public.documents where document_number='MEC-002'),current_date+10,'requested first issue date registered');
select is((select count(*)::integer from public.document_assignments a join public.documents d on d.id=a.document_id where d.document_number='MEC-002' and a.user_id=pg_temp.person(3) and a.status='active'),1,'new deliverable assigned to requesting engineer');
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
set local role authenticated;
select ok(public.can_upload_document(pg_temp.org(),pg_temp.project(),(select document_id from public.deliverable_requests where id=pg_temp.req())),'engineer can upload the approved additional deliverable');
select set_config('test.request',pg_temp.add_request()::text,true);
reset role;
update public.project_memberships set status='removed' where user_id=pg_temp.person(3);
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
set local role authenticated;
select is(pg_temp.review('approve','MEC-003'),'superseded','removed engineer cannot gain a new assignment through an old request');
reset role;
select is((select count(*)::integer from public.documents),2,'stale engineer approval creates nothing');
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
set local role authenticated;
select is((select count(*)::integer from public.deliverable_requests),0,'removed member loses request access');
select throws_ok($$select pg_temp.add_request()$$,'42501',null,'removed engineer cannot send new requests');
reset role;
select * from finish();
rollback;
