import io

import pytest
from pypdf import PdfReader

from app.transmittals import _attestation_reference, build_transmittal_pdf


def sample_transmittal(document_count=20):
    package = {
        "id": "transmittal-id", "package_number": "TR-DEMO-001", "purpose": "Issued for Approval",
        "manifest": {
            "issued_at": "2026-09-12T12:00:00+00:00", "document_count": document_count,
            "recipient": {"company": "Example Client", "contact": "Client Document Control"},
            "issuer": {"user_id": "dcc-user", "name": "A. Controller", "email": "dcc@example.test"},
            "project": {"code": "DEMO-01", "name": "Export Pipeline FEED", "organisation": "Example Engineering"},
        },
    }
    documents = [
        {"revision_id": f"revision-{i}", "document_number": f"DEMO-DOC-{i:03}",
         "discipline": "Process", "revision_code": "A01", "issue_status": "Issued for Approval"}
        for i in range(1, document_count + 1)
    ]
    return package, documents


@pytest.mark.parametrize("seal_expected", [False, True])
def test_generated_branding_is_only_in_the_footer_on_every_page(seal_expected):
    package, documents = sample_transmittal()
    pdf = build_transmittal_pdf(package, documents, electronic_seal_expected=seal_expected)
    reader = PdfReader(io.BytesIO(pdf))
    assert len(reader.pages) == 3  # Cover, continued schedule and acknowledgement.
    for number, page in enumerate(reader.pages, 1):
        fragments = []
        text = page.extract_text(visitor_text=lambda text, _cm, tm, _font, _size, values=fragments: values.append((text, tm[5])))
        assert text.lower().count("engicite") == 1
        assert "Generated by EngiCite" in text
        assert f"Page {number}" in text
        assert "TR-DEMO-001" in text
        assert all(y < 52 for value, y in fragments if "engicite" in value.lower())
        assert not any(value.strip().lower() in {"engi", "cite"} for value, _ in fragments)
        stream = page.get_contents().get_data()
        assert b"0 782 595 60 re f" not in stream
        assert b"0 782 9 60 re f" not in stream
    cover = reader.pages[0].extract_text()
    assert "SYSTEM-ISSUED ATTESTATION" in cover
    assert "Example Engineering" in cover
    assert "A. Controller" in cover
    assert "dcc@example.test" in cover
    assert "12 September 2026" in cover
    reference = _attestation_reference(package, documents, package["manifest"])
    assert reference in cover
    assert reference in reader.pages[-1].extract_text()
    assert "CLIENT ACKNOWLEDGEMENT" in reader.pages[-1].extract_text()
    assert "Signature" in reader.pages[-1].extract_text()
    if seal_expected:
        assert "Electronic organisation seal embedded" in cover
    else:
        assert "not a qualified electronic signature or seal" in cover
    schedule = "\n".join(page.extract_text() for page in reader.pages[:-1])
    for document in documents:
        assert schedule.count(document["document_number"]) == 1


@pytest.mark.parametrize("document_count", [0, 1, 13, 14, 41, 42, 70])
@pytest.mark.parametrize("message", [None, "Please review this document schedule. " * 50])
def test_schedule_pagination_keeps_all_documents_clear_of_attestation_and_footer(document_count, message):
    package, documents = sample_transmittal(document_count)
    package["manifest"]["message"] = message
    reader = PdfReader(io.BytesIO(build_transmittal_pdf(package, documents)))
    scheduled_numbers = []
    for index, page in enumerate(reader.pages[:-1]):
        fragments = []
        page.extract_text(visitor_text=lambda text, _cm, tm, _font, _size, values=fragments: values.append((text.strip(), tm[5])))
        for text, y in fragments:
            if text.startswith("DEMO-DOC-"):
                scheduled_numbers.append(text)
                # The row separator sits seven points below the text baseline.
                assert y - 7 >= (178 if index == 0 else 64)
    assert scheduled_numbers == [document["document_number"] for document in documents]
    assert "CLIENT ACKNOWLEDGEMENT" in reader.pages[-1].extract_text()


@pytest.mark.parametrize("seal_expected", [False, True])
def test_recipient_acknowledgement_only_requests_signature_and_date(seal_expected):
    package, documents = sample_transmittal()
    reader = PdfReader(io.BytesIO(build_transmittal_pdf(package, documents, electronic_seal_expected=seal_expected)))
    page = reader.pages[-1]
    text = page.extract_text()
    assert "I acknowledge receipt of the documents listed in this transmittal." in text
    assert text.split().count("Signature") == 1
    assert text.split().count("Date") == 1
    for removed in ["Recipient company", "Representative name", "Job title", "Date received", "Client comments", "exceptions", "Quote the transmittal", "Example Client"]:
        assert removed not in text
    assert package["package_number"] in text
    assert _attestation_reference(package, documents, package["manifest"]) in text
    assert "Generated by EngiCite" in text
    # Only two input lines; the other rules belong to the header and footer.
    operations = page.get_contents().operations
    assert sum(operator == b"S" for _operands, operator in operations) == 4
    # Recipient routing details still belong on the issued cover, not the form.
    assert "Example Client" in reader.pages[0].extract_text()
