import Link from "next/link";
import { FilePlus2, FileText, Search, ShieldCheck } from "lucide-react";
import { requireProject } from "@/lib/auth";
import { createDocument } from "../../../../actions";

const writable=new Set(["organisation_admin","project_admin","document_controller"]);
export default async function DocumentsPage({params,searchParams}:{params:Promise<{organisationId:string;projectId:string}>;searchParams:Promise<{q?:string}>}){
  const {organisationId,projectId}=await params; const {q=""}=await searchParams; const {supabase,access}=await requireProject(organisationId,projectId);
  const safeQ=q.replaceAll(/[,%()]/g,""); let query=supabase.from("documents").select("id,document_number,title,document_type,discipline,status,updated_at").eq("organisation_id",organisationId).eq("project_id",projectId).order("updated_at",{ascending:false}).limit(100);
  if(safeQ)query=query.or(`document_number.ilike.%${safeQ}%,title.ilike.%${safeQ}%`); const {data:docs}=await query; const canWrite=writable.has(String(access.role));
  return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0c5b45]">Master document register</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Controlled documents</h1><p className="mt-2 flex items-center gap-2 text-sm text-[#65736f]"><ShieldCheck size={15}/> Tenant and project scope enforced</p></div><form className="relative"><Search className="absolute left-3 top-3.5 text-[#89948f]" size={16}/><input className="ev-input w-72 pl-9" name="q" defaultValue={q} placeholder="Number or title"/></form></div>
    <div className={`mt-8 grid items-start gap-5 ${canWrite?"xl:grid-cols-[1fr_350px]":""}`}><section className="ev-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-[#dfe7e3] bg-[#f8faf8] text-[10px] uppercase tracking-[.14em] text-[#65736f]"><tr><th className="px-5 py-4">Document</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Discipline</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Updated</th></tr></thead><tbody>{docs?.map(d=><tr key={d.id} className="border-b border-[#edf1ef] last:border-0"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#e8f1ed] text-[#0c5b45]"><FileText size={16}/></span><div><Link href={`/app/${organisationId}/projects/${projectId}/documents/${d.id}`} className="text-xs font-bold text-[#0c5b45] hover:underline">{d.document_number}</Link><p className="mt-1 max-w-md truncate text-sm font-medium">{d.title}</p></div></div></td><td className="px-5 py-4 text-sm">{d.document_type}</td><td className="px-5 py-4 text-sm">{d.discipline}</td><td className="px-5 py-4"><span className="rounded-full bg-[#eef4f1] px-2.5 py-1 text-xs font-semibold">{d.status}</span></td><td className="px-5 py-4 text-xs text-[#65736f]">{new Date(d.updated_at).toLocaleDateString()}</td></tr>)}{!docs?.length&&<tr><td colSpan={5} className="p-12 text-center text-[#65736f]">No documents match this register view.</td></tr>}</tbody></table></div></section>
      {canWrite&&<form action={createDocument} className="ev-card p-6"><input type="hidden" name="organisationId" value={organisationId}/><input type="hidden" name="projectId" value={projectId}/><div className="flex items-center gap-2"><FilePlus2 size={18} className="text-[#0c5b45]"/><h2 className="font-semibold">Register document</h2></div><Field n="documentNumber" l="Document number" p="EV-PIP-001"/><Field n="title" l="Title"/><Field n="documentType" l="Document type" p="Specification"/><Field n="discipline" l="Discipline" p="Piping"/><button className="ev-button mt-5 w-full">Create document</button><p className="mt-3 text-xs leading-5 text-[#65736f]">Open the record after creation to upload its first revision.</p></form>}
    </div></div>
}
function Field({n,l,p}:{n:string;l:string;p?:string}){return <label className="mt-4 block"><span className="ev-label">{l}</span><input className="ev-input" name={n} placeholder={p} required/></label>}
