import Link from "next/link";
import { FileText, Layers3, List, MessageSquareText, Search, Settings2, ShieldCheck } from "lucide-react";
import { requireProject } from "@/lib/auth";
import { can } from "@/lib/permissions";
import { ProjectInvite } from "@/components/project-invite";
import { DocumentCreateForm } from "@/components/document-create-form";

const writable=new Set(["organisation_admin","project_admin","document_controller"]);const PAGE_SIZE=25;
type Params={q?:string;page?:string;discipline?:string;documentType?:string;status?:string;area?:string;view?:string};
type Doc={id:string;document_number:string;title:string;document_type:string;discipline:string;status:string;area:string|null;system:string|null;work_package:string|null;updated_at:string};
type Category={code:string;name:string;kind:string};
const clean=(value:string)=>value.replaceAll(/[,%()]/g,"").slice(0,100);

export default async function DocumentsPage({params,searchParams}:{params:Promise<{organisationId:string;projectId:string}>;searchParams:Promise<Params>}){
 const {organisationId,projectId}=await params;const filters=await searchParams;const q=clean(filters.q??"");const discipline=clean(filters.discipline??"");const documentType=clean(filters.documentType??"");const status=clean(filters.status??"");const area=clean(filters.area??"");const view=filters.view==="grouped"?"grouped":"flat";const page=Math.max(1,Number.parseInt(filters.page??"1",10)||1);const {supabase,access}=await requireProject(organisationId,projectId);
 const [{data:categories},{data:metadata}]=await Promise.all([
  supabase.from("document_categories").select("code,name,kind").eq("organisation_id",organisationId).eq("is_active",true).order("sort_order"),
  supabase.from("documents").select("discipline,document_type,status,area").eq("organisation_id",organisationId).eq("project_id",projectId).limit(5000)
 ]);
 const from=(page-1)*PAGE_SIZE;let query=supabase.from("documents").select("id,document_number,title,document_type,discipline,status,area,system,work_package,updated_at",{count:"exact"}).eq("organisation_id",organisationId).eq("project_id",projectId).order("discipline").order("document_number").range(from,from+PAGE_SIZE-1);
 if(q)query=query.or(`document_number.ilike.%${q}%,title.ilike.%${q}%`);if(discipline)query=query.eq("discipline",discipline);if(documentType)query=query.eq("document_type",documentType);if(status)query=query.eq("status",status);if(area)query=query.eq("area",area);
 const {data,count}=await query;const docs=(data??[]) as Doc[];const total=count??0;const totalPages=Math.max(1,Math.ceil(total/PAGE_SIZE));const role=String(access.role);const canWrite=writable.has(role);const canManage=role==="organisation_admin"||role==="project_admin";const categoryRows=(categories??[]) as Category[];
 const disciplines=categoryRows.filter(c=>c.kind==="discipline");const documentTypes=categoryRows.filter(c=>c.kind==="document_type");const distinct=(key:"discipline"|"document_type"|"status"|"area")=>[...new Set((metadata??[]).map(row=>row[key]).filter(Boolean) as string[])].sort();const disciplineCounts=new Map<string,number>();(metadata??[]).forEach(row=>disciplineCounts.set(row.discipline,(disciplineCounts.get(row.discipline)??0)+1));
 const url=(changes:Partial<Params>)=>`?${new URLSearchParams(Object.entries({...filters,...changes}).filter(([,v])=>v&&v!=="1") as [string,string][]).toString()}`;
 const groups=[...new Set(docs.map(d=>d.discipline))].sort();
 return <div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8733f]">Master document register</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Engineering deliverables</h1><p className="mt-2 flex items-center gap-2 text-sm text-[#617083]"><ShieldCheck size={15}/> Organised by discipline, type, area and system</p></div><div className="flex flex-wrap gap-2">{can(String(access.role),"ai:use")&&<Link href={`/app/${organisationId}/projects/${projectId}/chat`} className="ev-button inline-flex items-center gap-2 px-4"><MessageSquareText size={16}/> Ask EngiCite</Link>}<Link href={`/app/${organisationId}/projects/${projectId}/search`} className="ev-button-secondary inline-flex items-center gap-2 px-4"><Search size={16}/> Engineering search</Link>{role==="organisation_admin"&&<Link href={`/app/${organisationId}/settings/document-categories`} className="ev-button-secondary inline-flex items-center gap-2 px-4"><Settings2 size={16}/> Categories</Link>}</div></header>
 <form className="ev-card mt-6 grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-[2fr_repeat(4,1fr)_auto]"><input type="hidden" name="view" value={view}/><label><span className="ev-label">Search</span><input className="ev-input" name="q" defaultValue={q} placeholder="Number or title"/></label><Filter name="discipline" label="Discipline" value={discipline} values={[...new Set([...disciplines.map(c=>c.name),...distinct("discipline")])].sort()}/><Filter name="documentType" label="Document type" value={documentType} values={[...new Set([...documentTypes.map(c=>c.name),...distinct("document_type")])].sort()}/><Filter name="status" label="Status" value={status} values={distinct("status")}/><Filter name="area" label="Area" value={area} values={distinct("area")}/><button className="ev-button self-end">Apply filters</button></form>
 <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Link href={url({view:"flat",page:"1"})} className={view==="flat"?"ev-button":"ev-button-secondary"}><List size={16}/> Flat register</Link><Link href={url({view:"grouped",page:"1"})} className={view==="grouped"?"ev-button":"ev-button-secondary"}><Layers3 size={16}/> Group by discipline</Link>{(q||discipline||documentType||status||area)&&<Link href={`?view=${view}`} className="ev-button-secondary">Clear filters</Link>}</div><p className="text-sm font-semibold text-[#617083]">{total} matching document{total===1?"":"s"}</p></div>
 <div className={`mt-5 grid items-start gap-5 ${canWrite?"xl:grid-cols-[230px_1fr_350px]":"xl:grid-cols-[230px_1fr]"}`}><aside className="ev-card overflow-hidden"><div className="border-b border-[#dfe7e3] p-4"><p className="ev-label">Disciplines</p></div><nav className="max-h-[650px] overflow-y-auto p-2"><Link href={url({discipline:"",page:"1"})} className={`flex justify-between rounded-lg px-3 py-2 text-sm ${!discipline?"bg-[#e8f1ed] font-bold text-[#0c5b45]":"hover:bg-[#f5f7f6]"}`}><span>All disciplines</span><span>{metadata?.length??0}</span></Link>{[...new Set([...disciplines.map(c=>c.name),...distinct("discipline")])].sort().map(name=><Link key={name} href={url({discipline:name,page:"1"})} className={`mt-1 flex justify-between rounded-lg px-3 py-2 text-sm ${discipline===name?"bg-[#e8f1ed] font-bold text-[#0c5b45]":"hover:bg-[#f5f7f6]"}`}><span>{name}</span><span>{disciplineCounts.get(name)??0}</span></Link>)}</nav></aside>
 <section>{view==="grouped"?<div className="space-y-5">{groups.map(group=><RegisterTable key={group} title={group} docs={docs.filter(d=>d.discipline===group)} base={`/app/${organisationId}/projects/${projectId}`}/>)}</div>:<RegisterTable docs={docs} base={`/app/${organisationId}/projects/${projectId}`}/>}<Pagination page={page} totalPages={totalPages} total={total} href={url}/></section>
 {(canWrite||canManage)&&<aside className="space-y-5">{canWrite&&<DocumentCreateForm organisationId={organisationId} projectId={projectId} disciplines={disciplines} documentTypes={documentTypes}/>} {canManage&&<ProjectInvite organisationId={organisationId} projectId={projectId}/>}</aside>}</div></div>
}

function Filter({name,label,value,values}:{name:string;label:string;value:string;values:string[]}){return <label><span className="ev-label">{label}</span><select className="ev-input" name={name} defaultValue={value}><option value="">All</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function RegisterTable({docs,base,title}:{docs:Doc[];base:string;title?:string}){return <div className="ev-card overflow-hidden">{title&&<div className="flex items-center justify-between border-b border-[#dfe7e3] bg-[#f8faf8] px-5 py-4"><h2 className="font-semibold">{title}</h2><span className="rounded-full bg-[#e8f1ed] px-3 py-1 text-xs font-bold text-[#0c5b45]">{docs.length}</span></div>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-[#dfe7e3] bg-[#f8faf8] text-[10px] uppercase tracking-[.14em] text-[#65736f]"><tr><th className="px-5 py-4">Document</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Discipline</th><th className="px-5 py-4">Area / system</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Updated</th></tr></thead><tbody>{docs.map(d=><tr key={d.id} className="border-b border-[#edf1ef] last:border-0"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#e8f1ed] text-[#0c5b45]"><FileText size={16}/></span><div><Link href={`${base}/documents/${d.id}`} className="text-xs font-bold text-[#0c5b45] hover:underline">{d.document_number}</Link><p className="mt-1 max-w-sm truncate text-sm font-medium">{d.title}</p></div></div></td><td className="px-5 py-4 text-sm">{d.document_type}</td><td className="px-5 py-4 text-sm">{d.discipline}</td><td className="px-5 py-4 text-xs"><p>{d.area??"—"}</p>{d.system&&<p className="mt-1 text-[#65736f]">{d.system}</p>}</td><td className="px-5 py-4"><span className="rounded-full bg-[#eef4f1] px-2.5 py-1 text-xs font-semibold">{d.status}</span></td><td className="px-5 py-4 text-xs text-[#65736f]">{new Date(d.updated_at).toLocaleDateString()}</td></tr>)}{!docs.length&&<tr><td colSpan={6} className="p-12 text-center text-[#65736f]">No documents match this register view.</td></tr>}</tbody></table></div></div>}
function Pagination({page,totalPages,total,href}:{page:number;totalPages:number;total:number;href:(c:Partial<Params>)=>string}){return <div className="mt-3 flex items-center justify-between text-xs text-[#617083]"><span>{total} document{total===1?"":"s"} · Page {page} of {totalPages}</span><div className="flex gap-2">{page>1?<Link className="ev-button-secondary" href={href({page:String(page-1)})}>Previous</Link>:<span className="rounded-lg border px-3 py-2 text-[#a3aaa6]">Previous</span>}{page<totalPages?<Link className="ev-button-secondary" href={href({page:String(page+1)})}>Next</Link>:<span className="rounded-lg border px-3 py-2 text-[#a3aaa6]">Next</span>}</div></div>}
