import Link from "next/link";
import { ArrowRight, Building2 } from "lucide-react";
import { requireUser } from "@/lib/auth";
import {projectHomePath,roleLabel} from "@/lib/role-experience";
import {ProjectLogo} from "@/components/project-logo";

// @ts-expect-error Supabase RPC rows are unknown without generated database types.

export default async function AllProjectsPage(){const {supabase}=await requireUser();const [{data:projects,error},{data:orgs}]=await Promise.all([supabase.from("project_access").select("organisation_id,project_id,code,name,role").order("name"),supabase.rpc("get_my_organisations")]);if(error)throw new Error(`Project access failed: ${error.code}`);const organisations=new Map((orgs??[]).map((org:{organisation_id:string;name:string})=>[org.organisation_id,org.name]));return <div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8733f]">Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Your projects</h1><p className="mt-2 text-[#617083]">Each project opens directly in the workspace assigned to your role.</p><section className="mt-8 grid gap-3">{projects?.length?projects.map(project=><Link href={projectHomePath(project.organisation_id,project.project_id,String(project.role))} key={project.project_id} className="ev-card flex items-center gap-4 p-5 transition hover:-translate-y-0.5"><span className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-xl border border-[#dfe7e3] bg-white p-1.5 text-[#e8733f]"><ProjectLogo organisationId={project.organisation_id} projectId={project.project_id} name={project.name} size={48} className="size-full object-contain"/></span><div className="min-w-0 flex-1"><p className="flex items-center gap-2 text-xs text-[#617083]"><Building2 size={13}/>{organisations.get(project.organisation_id)??"Organisation"}</p><h2 className="mt-1 font-semibold"><span className="mr-2 text-[#e8733f]">{project.code}</span>{project.name}</h2><p className="mt-1 text-xs text-[#617083]">{roleLabel(String(project.role))}</p></div><ArrowRight size={18}/></Link>):<div className="ev-card p-10 text-center text-[#617083]">No authorised projects yet.</div>}</section></div>}
