"use client";

import {HelpTip} from "@/components/help-tip";
import {useActionState,useState} from "react";
import {Archive,DatabaseBackup,Eye,HardDriveDownload,RotateCcw,Trash2} from "lucide-react";
import {enterAdminRolePreview} from "@/app/app/governance-actions";
import {requestProjectBackup,restoreTrashedProject,setProjectArchived,trashProject,updateProjectBackupPolicy,type MutationState} from "@/app/app/actions";
import {scopedRoleLabel} from "@/lib/role-experience";

type Connection={id:string;provider:string;display_name:string};
type Policy={enabled:boolean;provider:string;connection_id:string|null;schedule_frequency:string;weekday:number;run_time:string;destination_path:string;next_run_at:string|null}|null;
type Backup={id:string;provider:string;trigger_kind:string;state:string;byte_size:number|null;external_location:string|null;error_code:string|null;created_at:string;completed_at:string|null};
export type PreviewMember={user_id:string;display_name:string;email:string;role:string;disciplines:string[]};

export function ProjectGovernanceControls({project,policy,backups,connections,members=[]}:{project:{id:string;organisationId:string;code:string;name:string;status:string;purgeAfter:string|null};policy:Policy;backups:Backup[];connections:Connection[];members?:PreviewMember[]}){
 return <div className="space-y-6">
  <RolePreview project={project} members={members}/>
  <BackupControls project={project} policy={policy} backups={backups} connections={connections}/>
  <Lifecycle project={project}/>
 </div>;
}

export function RolePreview({project,members}:{project:{id:string;organisationId:string};members:PreviewMember[]}){
 const [state,action,pending]=useActionState(enterAdminRolePreview,undefined);
 const [search,setSearch]=useState('');
 const eligible=members.filter(member=>['project_admin','document_controller','engineer'].includes(member.role));
 const visible=eligible.filter(member=>`${member.display_name} ${member.email} ${member.disciplines.join(' ')} ${scopedRoleLabel(member.role,member.disciplines)}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="ev-card p-6"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#fff1e9] text-[#e8733f]"><Eye size={19}/></span><div><h2 className="font-semibold">Audited member preview <HelpTip label="Live member preview">See a team member’s live project dashboard, assignments and permitted data. You stay signed in as the administrator; uploads, approvals and all other changes are disabled. Each 30-minute support session is audited.</HelpTip></h2></div></div>
 {eligible.length?<form action={action} className="mt-5 space-y-4"><input type="hidden" name="organisationId" value={project.organisationId}/><input type="hidden" name="projectId" value={project.id}/>
 <label className="block"><span className="ev-label">Find a team member</span><input type="search" className="ev-input" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Name, work email or discipline"/></label>
 <label className="block"><span className="ev-label">View this member’s project workspace</span><select name="memberId" className="ev-input" required defaultValue=""><option value="" disabled>Select a team member</option>{visible.map(member=><option key={member.user_id} value={member.user_id}>{member.display_name||member.email} · {scopedRoleLabel(member.role,member.disciplines)} · {member.email}</option>)}</select></label>
 <label className="block"><span className="ev-label">Support reason (recorded in the audit log)</span><textarea name="reason" className="ev-input" required minLength={5} maxLength={500} placeholder="For example: investigate missing MDR assignments"/></label>
 {state?.message&&<p role="alert" className="text-sm text-[#a53724]">{state.message}</p>}
 <button className="ev-button-secondary" disabled={pending||!visible.length}><Eye size={15}/>{pending?'Opening secure preview…':'Open live read-only preview'}</button></form>:<p className="mt-5 text-sm text-[#617083]">No active Project Manager, DCC or Discipline Engineer is available to preview. Invite and appoint a team member first.</p>}
 </section>;
}

function BackupControls({project,policy,backups,connections}:{project:{id:string;organisationId:string};policy:Policy;backups:Backup[];connections:Connection[]}){
 const [manualState,manualAction,manualPending]=useActionState<MutationState,FormData>(requestProjectBackup,undefined);
 const [policyState,policyAction,policyPending]=useActionState<MutationState,FormData>(updateProjectBackupPolicy,undefined);
 const [provider,setProvider]=useState(policy?.provider??"engicite");
 const matching=connections.filter(connection=>connection.provider===provider);
 const destination=policy?.destination_path??"/EngiCite Backups";
 return <section className="ev-card overflow-hidden"><div className="border-b border-[#e7ece9] p-6"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#e8f1ed] text-[#0c5b45]"><DatabaseBackup size={19}/></span><div><h2 className="font-semibold">Project backups <HelpTip label="Project backups">Create a portable ZIP containing the project record, MDR, all stored revisions, planning data and audit evidence. This complements—not replaces—EngiCite disaster-recovery backups.</HelpTip></h2></div></div></div>
  <div className="grid gap-6 p-6 xl:grid-cols-2"><form action={manualAction} className="rounded-xl border border-[#dfe7e3] p-5"><input type="hidden" name="organisationId" value={project.organisationId}/><input type="hidden" name="projectId" value={project.id}/><h3 className="font-semibold">Manual backup now</h3><DestinationFields provider={provider} setProvider={setProvider} connections={matching} destination={destination}/>{manualState?.message&&<Status state={manualState}/>}<button className="ev-button mt-5" disabled={manualPending}>{manualPending?"Building secure archive…":"Create project backup"}</button></form>
  <form action={policyAction} className="rounded-xl border border-[#dfe7e3] p-5"><input type="hidden" name="organisationId" value={project.organisationId}/><input type="hidden" name="projectId" value={project.id}/><h3 className="font-semibold">Automatic backup schedule</h3><input type="hidden" name="enabled" value="false"/><label className="mt-4 flex items-center gap-3 rounded-xl bg-[#f5f8f6] p-3 text-sm font-semibold"><input type="checkbox" name="enabled" value="true" defaultChecked={policy?.enabled}/>Enable scheduled backups</label><ScheduleDestination policy={policy} connections={connections}/>{policyState?.message&&<Status state={policyState}/>}<button className="ev-button-secondary mt-5" disabled={policyPending}>{policyPending?"Saving…":"Save backup schedule"}</button></form></div>
  <div className="border-t border-[#e7ece9] p-6"><h3 className="font-semibold">Backup history</h3>{backups.length?<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wide text-[#617083]"><th className="pb-3">Created</th><th>Trigger</th><th>Destination</th><th>Status</th><th>Size</th><th></th></tr></thead><tbody>{backups.map(backup=><tr className="border-b last:border-0" key={backup.id}><td className="py-3">{new Date(backup.created_at).toLocaleString()}</td><td className="capitalize">{backup.trigger_kind}</td><td>{providerLabel(backup.provider)}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${backup.state==="failed"?"bg-[#fff0e9] text-[#a5452f]":"bg-[#e8f1ed] text-[#0c5b45]"}`}>{backup.state.replaceAll("_"," ")}</span>{backup.error_code&&<p className="mt-1 text-xs text-[#a5452f]">Backup could not be completed. Please retry or contact EngiCite support.</p>}</td><td>{formatBytes(backup.byte_size)}</td><td className="text-right">{backup.byte_size&&backup.state!=="failed"?<a className="inline-flex items-center gap-1.5 font-semibold text-[#0c5b45]" href={`/api/v1/organisations/${project.organisationId}/projects/${project.id}/backups/${backup.id}/download`}><HardDriveDownload size={15}/> Download</a>:null}</td></tr>)}</tbody></table></div>:<p className="mt-3 text-sm text-[#617083]">No project backup has been created yet.</p>}</div>
 </section>;
}

function DestinationFields({provider,setProvider,connections,destination}:{provider:string;setProvider:(value:string)=>void;connections:Connection[];destination:string}){return <><label className="mt-4 block"><span className="ev-label">Destination</span><select className="ev-input" name="provider" value={provider} onChange={event=>setProvider(event.target.value)}><option value="engicite">EngiCite secure archive</option><option value="sharepoint">Company SharePoint</option><option value="zoho_workdrive">Zoho WorkDrive</option></select></label><label className="mt-4 block"><span className="ev-label">Company drive connection</span><select className="ev-input" name="connectionId" required={provider!=="engicite"} disabled={provider==="engicite"}><option value="">{provider==="engicite"?"Not required":"Choose a connected company drive"}</option>{connections.map(connection=><option value={connection.id} key={connection.id}>{connection.display_name}</option>)}</select></label>{provider!=="engicite"&&!connections.length&&<p className="mt-2 text-xs font-semibold text-[#a5452f]">No active {providerLabel(provider)} connection is registered for this organisation yet.</p>}<label className="mt-4 block"><span className="ev-label">Destination folder</span><input className="ev-input" name="destinationPath" defaultValue={destination} required/></label></>}

function ScheduleDestination({policy,connections}:{policy:Policy;connections:Connection[]}){const [provider,setProvider]=useState(policy?.provider??"engicite");const matching=connections.filter(connection=>connection.provider===provider);return <><DestinationFields provider={provider} setProvider={setProvider} connections={matching} destination={policy?.destination_path??"/EngiCite Backups"}/><div className="mt-4 grid gap-3 sm:grid-cols-3"><label><span className="ev-label">Frequency</span><select className="ev-input" name="frequency" defaultValue={policy?.schedule_frequency??"weekly"}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label><span className="ev-label">Day</span><select className="ev-input" name="weekday" defaultValue={policy?.weekday??5}>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map((day,index)=><option value={index} key={day}>{day}</option>)}</select></label><label><span className="ev-label">Time</span><input className="ev-input" type="time" name="runTime" defaultValue={(policy?.run_time??"18:00").slice(0,5)}/></label></div>{policy?.next_run_at&&<p className="mt-3 text-xs text-[#617083]">Next scheduled run: {new Date(policy.next_run_at).toLocaleString()}</p>}</>}

function Lifecycle({project}:{project:{id:string;organisationId:string;code:string;name:string;status:string;purgeAfter:string|null}}){const [state,action,pending]=useActionState<MutationState,FormData>(trashProject,undefined);const [confirmation,setConfirmation]=useState("");const [acknowledged,setAcknowledged]=useState(false);if(project.status==="trashed")return <section className="ev-card border-[#efc6b4] bg-[#fff9f5] p-6"><div className="flex items-center gap-2 text-[#a5452f]"><Trash2 size={18}/><h2 className="font-semibold">Project is in trash</h2></div><p className="mt-2 text-sm text-[#6f4b45]">Project members cannot access it. Its records and files remain recoverable{project.purgeAfter?` until ${new Date(project.purgeAfter).toLocaleDateString()}`:""}.</p><form action={restoreTrashedProject} className="mt-4"><input type="hidden" name="organisationId" value={project.organisationId}/><input type="hidden" name="projectId" value={project.id}/><button className="ev-button-secondary"><RotateCcw size={16}/> Restore project</button></form></section>;
 return <section className="grid gap-5 lg:grid-cols-2"><form action={setProjectArchived} className="ev-card border-[#efc6b4] p-6"><input type="hidden" name="organisationId" value={project.organisationId}/><input type="hidden" name="projectId" value={project.id}/><input type="hidden" name="archived" value={String(project.status!=="archived")}/><div className="flex items-center gap-2"><Archive size={18}/><h2 className="font-semibold">{project.status==="archived"?"Restore archived project":"Archive project"}</h2></div><p className="mt-2 text-sm leading-6 text-[#617083]">{project.status==="archived"?"Return the project to active portfolio operation.":"Pause active work while keeping the entire record, team and audit history."}</p><button className="ev-button-secondary mt-4">{project.status==="archived"?"Restore project":"Archive project"}</button></form><form action={action} className="ev-card border-[#ef9b8a] bg-[#fffafa] p-6"><input type="hidden" name="organisationId" value={project.organisationId}/><input type="hidden" name="projectId" value={project.id}/><div className="flex items-center gap-2 text-[#a53724]"><Trash2 size={18}/><h2 className="font-semibold">Delete project</h2></div><p className="mt-2 text-sm leading-6 text-[#6f4b45]">Moves the project to recoverable trash for 30 days and immediately removes member access. Records are not physically destroyed by this action.</p><label className="mt-4 block"><span className="ev-label">Type <strong>{project.code}</strong> to confirm</span><input className="ev-input" name="confirmationCode" value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off" required/></label><label className="mt-4 flex items-start gap-3 text-sm text-[#6f4b45]"><input className="mt-1" type="checkbox" name="acknowledge" value="yes" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)} required/><span>I understand that all project members will immediately lose access.</span></label>{state?.message&&<p className="mt-3 text-sm text-[#a53724]">{state.message}</p>}<button className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#a53724] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40" disabled={pending||confirmation!==project.code||!acknowledged}><Trash2 size={16}/>{pending?"Moving to trash…":"Delete project"}</button></form></section>}

function Status({state}:{state:Exclude<MutationState,undefined>}){return <p className="mt-3 rounded-lg bg-[#f3f7f5] p-3 text-sm text-[#0c5b45]" role="status">{state.message}</p>}
function providerLabel(provider:string){return provider==="sharepoint"?"SharePoint":provider==="zoho_workdrive"?"Zoho WorkDrive":"EngiCite archive"}
function formatBytes(value:number|null){if(!value)return "—";if(value<1024*1024)return `${Math.round(value/1024)} KB`;return `${(value/(1024*1024)).toFixed(1)} MB`}
