"use client";

import Link from "next/link";
import {Bell,Building2,ChartNoAxesColumnIncreasing,ChevronDown,ClipboardCheck,FileSearch,FileStack,FileText,FolderKanban,LayoutDashboard,MessageSquareText,Package,Settings,UserCheck,Users} from "lucide-react";
import {usePathname} from "next/navigation";
import {useEffect,useState} from "react";
import type {WorkspacePersona} from "@/lib/role-experience";
import {ProjectLogo} from "@/components/project-logo";

type Context={role:string;roleLabel:string;persona:WorkspacePersona;project:{code:string;name:string};pendingReviewCount:number};
type ScopedContext={projectId:string;value:Context};
type Item={key:string;href:string;label:string;icon:React.ReactNode;badge?:number};

export function WorkspaceNavigation({unreadCount=0}:{unreadCount?:number}){
 const pathname=usePathname();const [open,setOpen]=useState(false);const [scopedContext,setScopedContext]=useState<ScopedContext|null>(null);const uuid="[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}";const match=pathname.match(new RegExp(`^/app/(${uuid})(?:/projects/(${uuid}))?`,"i"));const organisationId=match?.[1];const projectId=match?.[2];
 useEffect(()=>{if(!organisationId||!projectId)return;const controller=new AbortController();const loadContext=()=>fetch(`/api/v1/organisations/${organisationId}/projects/${projectId}/workspace-context`,{cache:"no-store",signal:controller.signal}).then(response=>response.ok?response.json():null).then(value=>{if(value)setScopedContext({projectId,value:value as Context})}).catch(()=>undefined);void loadContext();const interval=window.setInterval(()=>void loadContext(),15000);window.addEventListener("focus",loadContext);return()=>{controller.abort();window.clearInterval(interval);window.removeEventListener("focus",loadContext)}},[organisationId,projectId]);
 const context=scopedContext&&scopedContext.projectId===projectId?scopedContext.value:null;const base=projectId?`/app/${organisationId}/projects/${projectId}`:"";const active=activeKey(pathname);const items=buildItems({organisationId,projectId,base,context,unreadCount});
 const links=items.map(item=>{const selected=active===item.key;return <Link key={item.key} href={item.href} onClick={()=>setOpen(false)} aria-current={selected?"page":undefined} className={`group mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${selected?"bg-white/[.12] text-white shadow-[inset_3px_0_0_#ed7138]":"text-white/60 hover:bg-white/[.07] hover:text-white"}`}><span className={`grid size-8 shrink-0 place-items-center rounded-lg transition ${selected?"bg-[#ed7138] text-white":"bg-white/[.055] text-white/55 group-hover:text-white"}`}>{item.icon}</span><span className="min-w-0 flex-1">{item.label}</span>{Boolean(item.badge)&&<span className="grid min-w-5 place-items-center rounded-full bg-[#ed7138] px-1 text-[10px] font-extrabold leading-5 text-white">{(item.badge??0)>99?"99+":item.badge}</span>}</Link>});
 const workspaceLabel=context?.roleLabel??"Secure workspace";const workspaceDescription=context?.project?.code?`${context.project.code} · ${context.project.name}`:"Your authorised engineering work";
 return <><div className="sticky top-16 z-30 border-b border-white/10 bg-[#10243e] p-2.5 text-white shadow-lg md:hidden"><button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} className="flex w-full items-center justify-between rounded-xl border border-white/10 bg-white/[.07] px-3.5 py-2.5 text-sm font-semibold"><span className="flex items-center gap-2.5"><span className={`grid size-7 shrink-0 place-items-center overflow-hidden rounded-lg ${projectId?"bg-white p-1 text-[#ed7138]":"bg-[#ed7138]"}`}>{projectId&&organisationId?<ProjectLogo organisationId={organisationId} projectId={projectId} name={context?.project?.name??"Project"} size={28} className="size-full object-contain"/>:<FolderKanban size={15}/>}</span>{workspaceLabel}</span><ChevronDown size={17} className={`transition ${open?"rotate-180":""}`}/></button>{open&&<nav aria-label="Workspace" className="absolute left-2.5 right-2.5 top-[calc(100%+6px)] max-h-[70vh] overflow-y-auto rounded-2xl border border-white/10 bg-[#10243e] p-2.5 shadow-[0_24px_60px_rgba(5,19,36,.35)]">{links}</nav>}</div><aside style={{left:"max(0px, calc((100vw - min(2100px, 100vw)) / 2))"}} className="fixed bottom-0 top-16 z-30 hidden w-[248px] overflow-y-auto border-r border-white/[.07] bg-[linear-gradient(180deg,#10243e_0%,#0c1d32_100%)] p-4 text-white md:block 2xl:w-[264px] 2xl:p-5"><div className="mb-4 flex items-start gap-3 px-3 pt-2">{projectId&&organisationId&&<span className="grid size-9 shrink-0 place-items-center overflow-hidden rounded-xl bg-white p-1.5 text-[#ed7138]"><ProjectLogo organisationId={organisationId} projectId={projectId} name={context?.project?.name??"Project"} size={36} className="size-full object-contain"/></span>}<div className="min-w-0"><p className="text-[9px] font-extrabold uppercase tracking-[.22em] text-[#ff9a6d]">{workspaceLabel}</p><p className="mt-1.5 line-clamp-2 text-xs leading-5 text-white/45">{workspaceDescription}</p></div></div><nav aria-label="Workspace">{links}</nav><div className="mx-3 mt-8 rounded-xl border border-white/[.07] bg-white/[.035] p-3.5"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#ff9a6d]">Role separation</p><p className="mt-2 text-[11px] leading-5 text-white/45">This workspace shows only the responsibilities assigned to your current role.</p></div></aside></>;
}

function buildItems({organisationId,projectId,base,context,unreadCount}:{organisationId?:string;projectId?:string;base:string;context:Context|null;unreadCount:number}):Item[]{
 const global:Item[]=[{key:"organisations",href:"/app",label:"Organisations",icon:<Building2 size={17}/>}];
 const notifications:Item={key:"notifications",href:"/app/notifications",label:"Notifications",icon:<Bell size={17}/>,badge:unreadCount||undefined};
 if(!organisationId)return [...global,{key:"projects",href:"/app/projects",label:"Projects",icon:<FolderKanban size={17}/>},notifications];
 if(!projectId)return [...global,{key:"projects",href:`/app/${organisationId}`,label:"My project assignments",icon:<FolderKanban size={17}/>},notifications];
 const projects:Item={key:"projects",href:`/app/${organisationId}`,label:context?.persona==="management"?"All projects":"My project assignments",icon:<FolderKanban size={17}/>};
 if(!context)return [...global,projects,notifications];
 if(context.persona==="management")return [...global,projects,{key:"overview",href:`${base}/overview`,label:"Project overview",icon:<LayoutDashboard size={17}/>},{key:"progress",href:`${base}/progress`,label:"Progress & health",icon:<ChartNoAxesColumnIncreasing size={17}/>},{key:"reports",href:`${base}/reports`,label:"Project reports",icon:<FileText size={17}/>},{key:"team",href:`${base}/team`,label:"Team & resources",icon:<Users size={17}/>},notifications,{key:"settings",href:`${base}/settings`,label:"Project settings",icon:<Settings size={17}/>}];
 if(context.persona==="document_control")return [...global,projects,{key:"control",href:`${base}/control`,label:"DCC control centre",icon:<LayoutDashboard size={17}/>},{key:"documents",href:`${base}/documents`,label:"Master document register",icon:<FileStack size={17}/>},{key:"reviews",href:`${base}/reviews`,label:"Submission review",icon:<ClipboardCheck size={17}/>,badge:context.pendingReviewCount||undefined},{key:"team",href:`${base}/team`,label:"Discipline engineers",icon:<Users size={17}/>},{key:"progress",href:`${base}/progress`,label:"Delivery progress",icon:<ChartNoAxesColumnIncreasing size={17}/>},{key:"packages",href:`${base}/work-packages`,label:"Work packages",icon:<Package size={17}/>},notifications];
 if(context.persona==="engineering")return [...global,projects,{key:"assignments",href:`${base}/assignments`,label:"My deliverables",icon:<UserCheck size={17}/>},{key:"search",href:`${base}/search`,label:"Evidence search",icon:<FileSearch size={17}/>},{key:"chat",href:`${base}/chat`,label:"Ask EngiCite",icon:<MessageSquareText size={17}/>},notifications];
 return [...global,projects,{key:"documents",href:`${base}/documents`,label:"Project documents",icon:<FileStack size={17}/>},{key:"search",href:`${base}/search`,label:"Evidence search",icon:<FileSearch size={17}/>},notifications];
}

function activeKey(pathname:string){if(pathname.startsWith("/app/notifications"))return "notifications";if(pathname.endsWith("/overview"))return "overview";if(pathname.endsWith("/control"))return "control";if(pathname.endsWith("/reviews"))return "reviews";if(pathname.includes("/reports"))return "reports";if(pathname.endsWith("/team"))return "team";if(pathname.endsWith("/assignments"))return "assignments";if(pathname.includes("/work-packages"))return "packages";if(pathname.endsWith("/progress"))return "progress";if(pathname.endsWith("/search"))return "search";if(pathname.endsWith("/chat"))return "chat";if(pathname.endsWith("/settings"))return "settings";if(pathname==="/app/documents"||pathname.includes("/documents"))return "documents";if(pathname==="/app")return "organisations";return "projects"}
