"use client";
import Link from "next/link";
import { Building2, ChartNoAxesColumnIncreasing, ChevronDown, FileStack, FolderKanban, Package, Settings } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState } from "react";

export function WorkspaceNavigation(){
 const pathname=usePathname();const [open,setOpen]=useState(false);const uuid="[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}";const match=pathname.match(new RegExp(`^/app/(${uuid})(?:/projects/(${uuid}))?`,"i"));const organisationId=match?.[1];const projectId=match?.[2];
 const projectsHref=organisationId?`/app/${organisationId}`:"/app/projects";const documentsHref=projectId?`/app/${organisationId}/projects/${projectId}/documents`:organisationId?`/app/documents?organisationId=${organisationId}`:"/app/documents";
 const active=pathname.includes("/work-packages")?"packages":pathname.endsWith("/progress")?"progress":pathname.endsWith("/settings")?"settings":pathname==="/app/documents"||pathname.includes("/documents")?"documents":pathname==="/app/projects"||Boolean(organisationId)?"projects":"organisations";
 const settingsHref=projectId?`/app/${organisationId}/projects/${projectId}/settings`:organisationId?`/app/${organisationId}/settings`:null;const items=[{key:"organisations",href:"/app",label:"Organisations",icon:<Building2 size={17}/>},{key:"projects",href:projectsHref,label:"Projects",icon:<FolderKanban size={17}/>},{key:"documents",href:documentsHref,label:"Documents",icon:<FileStack size={17}/>},...(projectId?[{key:"progress",href:`/app/${organisationId}/projects/${projectId}/progress`,label:"Progress",icon:<ChartNoAxesColumnIncreasing size={17}/>},{key:"packages",href:`/app/${organisationId}/projects/${projectId}/work-packages`,label:"Work packages",icon:<Package size={17}/>}]:[]),...(settingsHref?[{key:"settings",href:settingsHref,label:"Settings",icon:<Settings size={17}/>}]:[])];
 const links=items.map(item=><Link key={item.key} href={item.href} onClick={()=>setOpen(false)} aria-current={active===item.key?"page":undefined} className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold transition ${active===item.key?"bg-white/15 text-white":"text-white/65 hover:bg-white/10 hover:text-white"}`}>{item.icon}{item.label}</Link>);
 return <><div className="border-b border-[#dce2e9] bg-[#10243e] p-3 text-white md:hidden"><button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} className="flex w-full items-center justify-between rounded-lg bg-white/10 px-4 py-3 text-sm font-semibold"><span className="flex items-center gap-2"><FolderKanban size={17}/>Workspace navigation</span><ChevronDown size={17} className={open?"rotate-180":""}/></button>{open&&<nav aria-label="Workspace" className="mt-2">{links}</nav>}</div><aside className="hidden min-h-[calc(100vh-68px)] border-r border-[#dce2e9] bg-[#10243e] p-4 text-white md:absolute md:left-0 md:top-0 md:block md:w-[240px]"><p className="px-3 pb-3 pt-3 text-[10px] font-extrabold uppercase tracking-[.2em] text-white/35">Workspace</p><nav aria-label="Workspace">{links}</nav><div className="mx-3 mt-8 border-t border-white/10 pt-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#ff9a6d]">Evidence standard</p><p className="mt-2 text-xs leading-5 text-white/45">Every AI answer must cite its document, revision and page.</p></div></aside></>
}
