import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, FileText } from "lucide-react";
import { requireProject } from "@/lib/auth";

export default async function RevisionPreviewPage({params}:{params:Promise<{organisationId:string;projectId:string;documentId:string;revisionId:string}>}){
  const {organisationId,projectId,documentId,revisionId}=await params;const {supabase}=await requireProject(organisationId,projectId);
  const {data:revision}=await supabase.from("document_revisions").select("id,revision_code,state,original_filename,detected_mime,declared_mime").eq("id",revisionId).eq("organisation_id",organisationId).eq("project_id",projectId).eq("document_id",documentId).maybeSingle();
  if(!revision||revision.state!=="ready")notFound();
  const {data:document}=await supabase.from("documents").select("document_number,title").eq("id",documentId).eq("organisation_id",organisationId).eq("project_id",projectId).maybeSingle();if(!document)notFound();
  const mime=revision.detected_mime??revision.declared_mime;const isPdf=mime==="application/pdf";const source=`/api/v1/organisations/${organisationId}/projects/${projectId}/documents/${documentId}/revisions/${revisionId}/preview`;
  if(isPdf)redirect(source);
  const {data:units}=await supabase.from("extracted_units").select("id,ordinal,locator_type,page_number,paragraph_number,sheet_name,cell_range,content").eq("revision_id",revisionId).order("ordinal").limit(500);
  return <div className="mx-auto max-w-7xl"><Link href={`/app/${organisationId}/projects/${projectId}/documents/${documentId}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#0c5b45]"><ArrowLeft size={16}/> Back to revision history</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8733f]">{document.document_number} · Revision {revision.revision_code}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{document.title}</h1><p className="mt-2 text-sm text-[#617083]">{revision.original_filename}</p></div><span className="rounded-full bg-[#eef4f1] px-3 py-1.5 text-xs font-semibold text-[#0c5b45]">Secure 5-minute preview</span></div>{isPdf?<iframe title={`Preview ${document.document_number} revision ${revision.revision_code}`} src={source} className="mt-6 h-[75vh] w-full rounded-xl border border-[#dce2e9] bg-white"/>:<section className="ev-card mt-6 overflow-hidden"><div className="flex items-center gap-2 border-b border-[#dfe7e3] p-5"><FileText size={18} className="text-[#0c5b45]"/><div><h2 className="font-semibold">Extracted content preview</h2><p className="mt-1 text-xs text-[#617083]">Rendered-page preview is pending; logical source locations are preserved below.</p></div></div><div className="max-h-[70vh] divide-y divide-[#edf1ef] overflow-y-auto">{units?.length?units.map(unit=><article key={unit.id} className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#e8733f]">{locator(unit)}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#24384f]">{unit.content}</p></article>):<p className="p-10 text-center text-[#617083]">No extractable content was produced for this format.</p>}</div></section>}</div>
}

function locator(unit:{locator_type:string;page_number:number|null;paragraph_number:number|null;sheet_name:string|null;cell_range:string|null}){if(unit.locator_type==="page")return `Page ${unit.page_number}`;if(unit.locator_type==="paragraph")return `Paragraph ${unit.paragraph_number}`;return `${unit.sheet_name??"Sheet"} · ${unit.cell_range??"Range"}`}
