import Link from "next/link";
import {ArrowLeft,Download} from "lucide-react";
import {notFound} from "next/navigation";
import {requireProject} from "@/lib/auth";
import {WorkPackageGenerate} from "@/components/work-package-generate";

export default async function PackagePage({params}:{params:Promise<{organisationId:string;projectId:string;packageId:string}>}){
 const {organisationId,projectId,packageId}=await params;const {supabase}=await requireProject(organisationId,projectId);
 const [{data:pack},{data:items}]=await Promise.all([supabase.from("work_packages").select("*").eq("id",packageId).eq("organisation_id",organisationId).eq("project_id",projectId).maybeSingle(),supabase.from("work_package_items").select("*").eq("work_package_id",packageId).order("discipline").order("document_number")]);if(!pack)notFound();
 const endpoint=`/api/v1/organisations/${organisationId}/projects/${projectId}/work-packages/${packageId}`;
 return <div className="mx-auto max-w-7xl"><Link href={`/app/${organisationId}/projects/${projectId}/work-packages`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#0c5b45]"><ArrowLeft size={16}/> Work packages</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#e8733f]">{pack.package_number} · VERSION {pack.version}</p><h1 className="mt-2 text-3xl font-semibold">{pack.name}</h1><p className="mt-2 text-sm capitalize text-[#617083]">{pack.state} · {pack.destination.replaceAll("_"," ")}</p></div>{pack.state==="ready"?<a className="ev-button" href={`${endpoint}/download`}><Download size={16}/> Download package</a>:pack.state==="frozen"||pack.state==="failed"?<WorkPackageGenerate endpoint={`${endpoint}/generate`}/>:null}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Card label="Included" value={Number(pack.manifest?.included??0)}/><Card label="Exceptions" value={Number(pack.manifest?.exceptions??0)}/><Card label="Destination" value={pack.destination.replaceAll("_"," ")}/></div><div className="ev-card mt-6 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-[#f8faf8] text-xs uppercase text-[#617083]"><tr><th className="p-4">Document</th><th>Discipline</th><th>Type</th><th>Revision</th><th>Issue status</th><th>Readiness</th></tr></thead><tbody>{items?.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-4 font-semibold">{item.document_number}</td><td>{item.discipline}</td><td>{item.document_type}</td><td>{item.revision_code??"—"}</td><td>{item.issue_status??"—"}</td><td className={item.inclusion_state==="included"?"font-semibold text-[#0c5b45]":"font-semibold text-[#a5452f]"}>{item.inclusion_state.replaceAll("_"," ")}</td></tr>)}</tbody></table></div></div>
}
function Card({label,value}:{label:string;value:string|number}){return <div className="ev-card p-5"><p className="ev-label">{label}</p><p className="text-2xl font-semibold capitalize">{value}</p></div>}
