import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,CalendarDays,CheckCircle2,Clock3,FileCheck2,FileText} from "lucide-react";
import {requireProject} from "@/lib/auth";
import {assessProjectHealth} from "@/lib/project-health";
import {DISCIPLINE_REPORT_COLUMN_OPTIONS,disciplineReportColumnLabel,disciplineReportColumnsQuery,disciplineReportValue,progressMovement,projectReportNumber,projectReportSnapshotSchema,resolveDisciplineReportColumns,type DisciplineReportColumn} from "@/lib/project-report";
import {OrganisationLogo} from "@/components/organisation-logo";
import {ProjectLogo} from "@/components/project-logo";
import {PrintReportButton} from "@/components/print-report-button";
import {ProjectSCurve} from "@/components/project-s-curve";
import {projectDeliveryStage,projectDeliveryStageLabel} from "@/lib/project-delivery-stage";

type ReportRow={id:string;report_number:number;period_start:string;period_end:string;generation_source:string;generated_at:string;snapshot:unknown};

export default async function ProjectReportPage({params,searchParams}:{params:Promise<{organisationId:string;projectId:string;reportId:string}>;searchParams:Promise<{columns?:string|string[]}>}){
  const [{organisationId,projectId,reportId},query]=await Promise.all([params,searchParams]);
  const {supabase}=await requireProject(organisationId,projectId);
  const {data}=await supabase.from("project_weekly_reports").select("id,report_number,period_start,period_end,generation_source,generated_at,snapshot").eq("organisation_id",organisationId).eq("project_id",projectId).eq("id",reportId).maybeSingle();
  if(!data)notFound();
  const report=data as ReportRow;
  const parsed=projectReportSnapshotSchema.safeParse(report.snapshot);
  if(!parsed.success)throw new Error("The saved project report is incomplete.");
  const snapshot=parsed.data;
  const deliveryStage=projectDeliveryStage(snapshot.identity.delivery_stage);
  const displayColumns=resolveDisciplineReportColumns(query.columns,snapshot.discipline_columns);
  const critical=snapshot.challenges.filter(issue=>issue.severity==="critical").length;
  const high=snapshot.challenges.filter(issue=>issue.severity==="high").length;
  const health=assessProjectHealth({deliverables:snapshot.summary.total_deliverables,completion:snapshot.summary.overall_progress,overdue:snapshot.summary.overdue_deliverables,highIssues:high,criticalIssues:critical});
  const weeklyIssuedGroups=Object.entries(snapshot.weekly_issued_deliverables.reduce<Record<string,(typeof snapshot.weekly_issued_deliverables)[number][]>>((groups,item)=>{(groups[item.discipline]??=[]).push(item);return groups},{})).sort(([left],[right])=>left.localeCompare(right));
  const lookaheadGroups=Object.entries(snapshot.lookahead.reduce<Record<string,(typeof snapshot.lookahead)[number][]>>((groups,item)=>{(groups[item.discipline]??=[]).push(item);return groups},{})).sort(([left],[right])=>left.localeCompare(right));
  const reportPath=`/app/${organisationId}/projects/${projectId}/reports/${reportId}`;
  const pdfPath=`/api/v1/organisations/${organisationId}/projects/${projectId}/reports/${reportId}/pdf?${disciplineReportColumnsQuery(displayColumns)}`;
  return <div className="project-report-page mx-auto max-w-[1500px]">
    <div className="report-no-print mb-5 flex flex-wrap items-center justify-between gap-3"><Link href={`/app/${organisationId}/projects/${projectId}/reports`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#0c5b45]"><ArrowLeft size={16}/> Project reports</Link><PrintReportButton href={pdfPath}/></div>
    <article className="project-report-sheet overflow-hidden rounded-[22px] border border-[#d6dee7] bg-white shadow-[0_18px_60px_rgba(16,36,62,.1)]">
      <header className="border-b-[5px] border-[#ed7138] bg-white px-6 py-6 text-[#10243e] sm:px-9 sm:py-8">
        <div className="grid grid-cols-[minmax(72px,1fr)_minmax(0,2.4fr)_minmax(72px,1fr)] items-center gap-3 sm:gap-6"><div className="flex flex-wrap items-center justify-start gap-2">{Array.from({length:snapshot.identity.client_logo_count},(_,index)=><span className="grid h-14 min-w-20 place-items-center overflow-hidden rounded-xl border border-[#d6dee7] bg-white p-2 sm:h-16 sm:min-w-24" key={index}><ProjectLogo organisationId={organisationId} projectId={projectId} name={snapshot.identity.project_name} index={index+1} size={80} className="max-h-12 w-auto object-contain"/></span>)}</div><div className="min-w-0 text-center"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#10243e]">{snapshot.identity.project_code}</p><h1 className="mt-2 text-lg font-semibold leading-tight tracking-[-.035em] sm:text-3xl">{snapshot.identity.project_name}</h1><p className="mt-2 text-[11px] leading-5 text-[#10243e]/65 sm:text-sm">{snapshot.identity.organisation_name} · Client: {snapshot.identity.client_name??"Not specified"}{snapshot.identity.facility_location?` · ${snapshot.identity.facility_location}`:""}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.1em] text-[#ed7138]">{projectDeliveryStageLabel(snapshot.identity.delivery_stage)} · 100% at {snapshot.identity.terminal_issue_status}</p></div><div className="flex items-center justify-end"><span className="grid h-14 min-w-20 place-items-center overflow-hidden rounded-xl border border-[#d6dee7] bg-white p-2 sm:h-16 sm:min-w-24"><OrganisationLogo organisationId={organisationId} name={snapshot.identity.organisation_name} size={80} className="max-h-12 w-auto object-contain"/></span></div></div>
        <div className="mt-7 grid gap-4 border-t border-[#10243e]/10 pt-5 sm:grid-cols-[minmax(0,1fr)_minmax(260px,.7fr)] sm:items-center"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#10243e]">Weekly project progress report</p><p className="mt-2 text-2xl font-semibold">{projectReportNumber(report.report_number)}</p><p className="mt-1 text-xs text-[#10243e]/60">{report.generation_source==="scheduled"?"Automatically generated":"Generated on demand"}</p></div><div className="rounded-xl border border-[#d6dee7] bg-[#f7f9fb] p-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#10243e]/60">Reporting period</p><p className="mt-2 flex items-center gap-2 font-semibold"><CalendarDays size={16} className="text-[#ed7138]"/>{formatDate(report.period_start)} - {formatDate(report.period_end)}</p><p className="mt-2 text-xs text-[#10243e]/60">Project timeline: {formatDate(snapshot.identity.planned_start_date)} - {formatDate(snapshot.identity.planned_end_date)}</p></div></div>
      </header>
      <div className="space-y-8 p-6 sm:p-9">
        <section><SectionHeading eyebrow="Progress Overview" title="Project health and delivery completion"/><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Project health" value={health}/><Metric label="Stage-weighted completion" value={`${snapshot.summary.overall_progress}%`} accent/><Metric label="Movement this week" value={progressMovement(snapshot.summary.progress_gain)}/><Metric label="Planned deliverables" value={snapshot.summary.planned_deliverables}/><Metric label="Terminal-stage issued" value={snapshot.summary.completed_deliverables}/><Metric label="Overdue" value={snapshot.summary.overdue_deliverables} warn={snapshot.summary.overdue_deliverables>0}/></div><p className="mt-3 rounded-xl border border-[#f0d5c8] bg-[#fff8f4] px-4 py-3 text-xs leading-5 text-[#6c5146]">This {deliveryStage?.label??"project"} report awards partial progress to accepted review and approval issues. A deliverable reaches 100% only at <strong>{snapshot.identity.terminal_issue_status}</strong>.</p></section>
        <section className="rounded-2xl border border-[#dfe7e3] bg-[#f8faf9] p-5 sm:p-6"><SectionHeading eyebrow="Project context" title="Project Brief"/><div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,.85fr)]"><div><h3 className="text-xs font-bold uppercase tracking-[.1em] text-[#617083]">Project introduction</h3><p className="mt-3 whitespace-pre-line text-sm leading-7 text-[#33485f]">{snapshot.identity.project_introduction??"No project introduction was recorded when this report was generated."}</p></div><div className="rounded-xl border border-[#dfe7e3] bg-white p-4"><h3 className="text-xs font-bold uppercase tracking-[.1em] text-[#617083]">Key objectives</h3>{snapshot.identity.key_objectives.length?<ul className="mt-3 space-y-2.5 text-sm leading-6 text-[#33485f]">{snapshot.identity.key_objectives.map((objective,index)=><li className="flex gap-3" key={`${index}-${objective}`}><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#ed7138]"/><span>{objective}</span></li>)}</ul>:<p className="mt-3 text-sm leading-6 text-[#617083]">No key objectives were recorded when this report was generated.</p>}</div></div></section>
        <section><SectionHeading eyebrow="Discipline performance" title="Lifetime scope, weekly delivery and cumulative position"/><DisciplineColumnPicker columns={displayColumns} reportPath={reportPath}/><div className="mt-4 overflow-x-auto rounded-xl border border-[#dfe7e3]"><table className="w-full text-left text-xs" style={{minWidth:`${Math.max(760,180+displayColumns.length*140)}px`}}><thead className="bg-[#f5f8f7] uppercase tracking-[.07em] text-[#617083]"><tr><th className="p-3.5">Discipline</th>{displayColumns.map(column=><th className="p-3.5" key={column}>{disciplineReportColumnLabel(column)}</th>)}</tr></thead><tbody>{snapshot.disciplines.map(row=><tr className="border-t border-[#edf1ef]" key={row.discipline}><td className="p-3.5 font-semibold text-[#24384f]">{row.discipline}</td>{displayColumns.map(column=><DisciplinePerformanceCell column={column} row={row} key={column}/>)}</tr>)}</tbody></table>{!snapshot.disciplines.length&&<p className="p-6 text-center text-sm text-[#617083]">No active MDR deliverables were available for this report.</p>}</div><p className="mt-3 text-xs leading-5 text-[#617083]">Actual completion is weighted by each deliverable&apos;s latest DCC-accepted issue stage. Terminal milestone variance compares deliverables at {snapshot.identity.terminal_issue_status} with the cumulative final-issue plan due at the reporting cut-off.</p></section>
        <section className="rounded-2xl border border-[#dfe7e3] p-5"><SectionHeading eyebrow="Past week" title="Delivery activity" compact/><div className="mt-5 grid gap-3 sm:grid-cols-3"><Activity icon={<FileText/>} value={snapshot.summary.weekly_acceptances} label="Stage issues this week"/><Activity icon={<FileCheck2/>} value={snapshot.summary.completed_deliverables} label="Terminal-stage issued"/><Activity icon={<Clock3/>} value={snapshot.summary.weekly_due} label="Final milestones due"/></div><p className="mt-5 rounded-xl bg-[#f5f8f7] p-4 text-sm leading-6 text-[#617083]">Stage-weighted completion movement is <strong className="text-[#24384f]">{progressMovement(snapshot.summary.progress_gain)}</strong>. {snapshot.summary.progress_gain===null?"This report establishes the first controlled baseline.":snapshot.summary.progress_gain>=0?"The project maintained or improved its controlled delivery position.":"The percentage reduced because MDR scope, accepted revision stages or the delivery plan changed."}</p></section>
        <section><SectionHeading eyebrow="Reporting week submissions" title="Issued deliverables"/><div className="mt-4 grid gap-4">{weeklyIssuedGroups.map(([discipline,items])=><article className="overflow-hidden rounded-xl border border-[#dfe7e3]" key={discipline}><header className="flex items-center justify-between gap-3 border-b border-[#dfe7e3] bg-[#f5f8f7] px-4 py-3"><h3 className="font-semibold text-[#10243e]">{discipline}</h3><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-[#617083]">{items.length} {items.length===1?"deliverable":"deliverables"}</span></header><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-white uppercase tracking-[.08em] text-[#617083]"><tr><th className="p-3.5">Issued date</th><th>Document</th><th>Revision</th><th className="pr-3.5">Issue status</th></tr></thead><tbody>{items.map(item=><tr className="border-t border-[#edf1ef]" key={`${item.document_number}-${item.revision_code}-${item.issued_at}`}><td className="p-3.5 font-semibold">{formatDateTime(item.issued_at)}</td><td><b className="text-[#0c5b45]">{item.document_number}</b><p className="mt-1 text-[#617083]">{item.title}</p></td><td className="font-semibold">{item.revision_code}</td><td className="pr-3.5">{item.issue_status}</td></tr>)}</tbody></table></div></article>)}{!weeklyIssuedGroups.length&&<div className="rounded-xl border border-[#dfe7e3] p-6 text-center text-sm text-[#617083]">No deliverable was issued during this reporting week.</div>}</div></section>
        <section><SectionHeading eyebrow="Next week look-ahead" title="Planned deliverable submissions"/><div className="mt-4 grid gap-4">{lookaheadGroups.map(([discipline,items])=><article className="overflow-hidden rounded-xl border border-[#dfe7e3]" key={discipline}><header className="flex items-center justify-between gap-3 border-b border-[#dfe7e3] bg-[#f5f8f7] px-4 py-3"><h3 className="font-semibold text-[#10243e]">{discipline}</h3><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-[#617083]">{items.length} {items.length===1?"deliverable":"deliverables"}</span></header><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-white uppercase tracking-[.08em] text-[#617083]"><tr><th className="p-3.5">Planned date</th><th>Document</th><th>Responsible</th><th className="pr-3.5">Required issue</th></tr></thead><tbody>{items.map(item=><tr className="border-t border-[#edf1ef]" key={`${item.document_number}-${item.planned_submission_date}`}><td className="p-3.5 font-semibold">{formatDate(item.planned_submission_date)}</td><td><b className="text-[#0c5b45]">{item.document_number}</b><p className="mt-1 text-[#617083]">{item.title}</p></td><td>{item.responsible_party??"Unassigned"}</td><td className="pr-3.5">{item.required_issue_status??"Not specified"}</td></tr>)}</tbody></table></div></article>)}{!lookaheadGroups.length&&<div className="rounded-xl border border-[#dfe7e3] p-6 text-center text-sm text-[#617083]">No MDR submission is planned in the next seven days.</div>}</div></section>
        <section><SectionHeading eyebrow="Challenges and actions" title="Open project issues requiring attention"/><div className="mt-4 grid gap-3">{snapshot.challenges.map((challenge,index)=><article className="rounded-xl border border-[#dfe7e3] p-4" key={`${index}-${challenge.title}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${severityTone(challenge.severity)}`}>{challenge.severity}</span><h3 className="mt-2 font-semibold">{challenge.title}</h3>{challenge.description&&<p className="mt-2 text-sm leading-6 text-[#617083]">{challenge.description}</p>}</div><div className="text-right text-xs text-[#617083]"><p>Owner: <b className="text-[#24384f]">{challenge.owner_name??"Unassigned"}</b></p><p className="mt-1">Target: {formatDate(challenge.due_date)}</p></div></div></article>)}{!snapshot.challenges.length&&<div className="flex items-center gap-3 rounded-xl bg-[#e8f1ed] p-5 text-sm font-semibold text-[#0c5b45]"><CheckCircle2 size={18}/>No open project challenge was recorded at generation time.</div>}</div></section>
        <section id="project-s-curve"><SectionHeading eyebrow="Schedule performance" title="Project delivery S-curve"/><p className="mt-2 max-w-3xl text-sm leading-6 text-[#617083]">The planned curve uses final-issue dates. The actual curve uses stage-weighted credit from the latest DCC-accepted revision, reaching 100% only at {snapshot.identity.terminal_issue_status}. The faint vertical guide identifies the current reporting week.</p><ProjectSCurve curve={snapshot.s_curve} totalDeliverables={snapshot.summary.planned_deliverables} reportPeriodEnd={report.period_end}/></section>
      </div>
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[#dfe7e3] bg-[#f8faf9] px-6 py-4 text-[10px] uppercase tracking-[.08em] text-[#617083] sm:px-9"><span>EngiCite controlled project report · {projectReportNumber(report.report_number)}</span><span>Generated {formatDateTime(report.generated_at)}</span></footer>
    </article>
  </div>;
}

function SectionHeading({eyebrow,title,compact=false}:{eyebrow:string;title:string;compact?:boolean}){return <div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#e8733f]">{eyebrow}</p><h2 className={`mt-1 font-semibold tracking-[-.02em] ${compact?"text-lg":"text-xl"}`}>{title}</h2></div>}
function DisciplineColumnPicker({columns,reportPath}:{columns:DisciplineReportColumn[];reportPath:string}){return <details className="report-no-print mt-4 overflow-hidden rounded-xl border border-[#b9d0c6] bg-[#f7fbf9]" open><summary className="cursor-pointer list-none px-4 py-3"><span className="block text-sm font-bold text-[#0c5b45]">Report column settings</span><span className="mt-1 block text-xs font-normal text-[#617083]">Choose the Discipline Performance columns shown in this generated report and its downloaded PDF.</span></summary><form method="get" action={reportPath} className="border-t border-[#d9e6e0] bg-white p-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{DISCIPLINE_REPORT_COLUMN_OPTIONS.map(option=><label className={`flex items-center gap-2 rounded-lg border px-3 py-2.5 text-xs font-semibold ${columns.includes(option.value)?"border-[#b9d0c6] bg-[#f2f8f5] text-[#0c5b45]":"border-[#e1e8e4] bg-[#fbfcfb] text-[#35485d]"}`} key={option.value}><input type="checkbox" name="columns" value={option.value} defaultChecked={columns.includes(option.value)} className="accent-[#0c5b45]"/><span>{option.label}</span></label>)}</div><div className="mt-4 flex flex-wrap items-center gap-3"><button className="ev-button" type="submit">Apply columns to this report</button><Link href={reportPath} className="ev-button-secondary">Restore saved columns</Link><span className="text-xs text-[#617083]">{columns.length} of {DISCIPLINE_REPORT_COLUMN_OPTIONS.length} columns displayed</span></div></form></details>}
function Metric({label,value,accent=false,warn=false}:{label:string;value:string|number;accent?:boolean;warn?:boolean}){return <div className={`rounded-xl border p-4 ${accent?"border-[#ed7138] bg-[#fff7f2]":warn?"border-[#efc6b4] bg-[#fff9f7]":"border-[#dfe7e3] bg-white"}`}><p className={`text-xl font-semibold ${accent?"text-[#e05f28]":warn?"text-[#a5452f]":"text-[#24384f]"}`}>{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[.1em] text-[#617083]">{label}</p></div>}
function Activity({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div><span className="text-[#e8733f]">{icon}</span><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] leading-4 text-[#617083]">{label}</p></div>}
function Variance({value}:{value:number}){return <span className={`font-semibold ${value<0?"text-[#a5452f]":value>0?"text-[#0c6b50]":"text-[#617083]"}`}>{value>0?`+${value}`:value}</span>}
function DisciplinePerformanceCell({row,column}:{row:Parameters<typeof disciplineReportValue>[0];column:DisciplineReportColumn}){const value=disciplineReportValue(row,column);if(column==="actual_completion")return <td className="p-3.5"><div className="flex min-w-28 items-center gap-2"><div className="h-2 flex-1 overflow-hidden rounded-full bg-[#e2e9e5]"><div className="h-full bg-[#0c5b45]" style={{width:`${Math.max(0,Math.min(100,row.actual_completion))}%`}}/></div><b>{value}</b></div></td>;if(column==="weekly_variance"||column==="project_variance")return <td className="p-3.5"><Variance value={Number(value)}/></td>;if(column==="weekly_variance_percent"||column==="cumulative_variance_percent"){const numeric=Number.parseFloat(value);return <td className={`p-3.5 font-semibold ${Number.isNaN(numeric)?"text-[#617083]":numeric<0?"text-[#a5452f]":numeric>0?"text-[#0c6b50]":"text-[#617083]"}`}>{value}</td>}return <td className={`p-3.5 ${column==="planned_completion"?"font-semibold":""}`}>{value}</td>}
function formatDate(value:string|null){return value?new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"Not planned"}
function formatDateTime(value:string){return new Date(value).toLocaleString(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function severityTone(value:string){if(value==="critical")return "bg-[#fde8e4] text-[#9b2c24]";if(value==="high")return "bg-[#fff0e9] text-[#a5452f]";if(value==="medium")return "bg-[#fff7dd] text-[#7a5a00]";return "bg-[#eef1f4] text-[#617083]"}
