import Link from "next/link";
import {redirect} from "next/navigation";
import {AlertTriangle,ClipboardCheck,FileClock,FilePlus2,FileStack,Send,UsersRound} from "lucide-react";
import {requireProject} from "@/lib/auth";
import {projectHomePath,roleLabel} from "@/lib/role-experience";
import {ProjectIssueForm} from "@/components/project-management-forms";
import {isSubmissionOverdue} from "@/lib/submission-deadlines";

type DocumentRow={id:string;document_number:string;discipline:string;planned_submission_date:string|null;document_revisions:{state:string;control_status:string}[]};
export default async function DocumentControlDashboard({params}:{params:Promise<{organisationId:string;projectId:string}>}){
  const {organisationId,projectId}=await params;const {supabase,access}=await requireProject(organisationId,projectId);const role=String(access.role);if(role!=="document_controller")redirect(projectHomePath(organisationId,projectId,role));
  const [{data:project},{data:documentRows},{data:issueRows},{data:teamRows}]=await Promise.all([
    supabase.from("projects").select("code,name,project_introduction,key_objectives,planned_end_date").eq("organisation_id",organisationId).eq("id",projectId).single(),
    supabase.from("documents").select("id,document_number,discipline,planned_submission_date,document_revisions(state,control_status)").eq("organisation_id",organisationId).eq("project_id",projectId).eq("lifecycle_status","active").order("discipline").order("document_number"),
    supabase.from("project_issues").select("id,severity,status").eq("organisation_id",organisationId).eq("project_id",projectId).neq("status","resolved"),
    supabase.rpc("get_project_team",{target_organisation:organisationId,target_project:projectId})
  ]);
  const docs=(documentRows??[]) as DocumentRow[];const today=new Date().toISOString().slice(0,10);const overdue=docs.filter(doc=>isSubmissionOverdue(doc.planned_submission_date,doc.document_revisions.map(revision=>revision.state),today)).length;const awaiting=docs.reduce((sum,doc)=>sum+doc.document_revisions.filter(revision=>revision.control_status==="submitted").length,0);const unsubmitted=docs.filter(doc=>!doc.document_revisions.some(revision=>revision.state!=="pending_upload")).length;const engineers=((teamRows??[]) as {role:string}[]).filter(member=>member.role==="engineer").length;const disciplineCounts=new Map<string,number>();docs.forEach(doc=>disciplineCounts.set(doc.discipline,(disciplineCounts.get(doc.discipline)??0)+1));
  return <div className="mx-auto max-w-[1450px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8733f]">{roleLabel(role)} workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{project?.code} · Document control centre</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#617083]">Populate and maintain the MDR, assign deliverables to Project Manager-appointed discipline engineers, review submissions and control final work packages.</p></div><div className="flex flex-wrap gap-2"><Link className="ev-button-secondary" href={`/app/${organisationId}/projects/${projectId}/work-packages/transmittals/new`}><Send size={16}/> Transmit documents</Link><Link className="ev-button" href={`/app/${organisationId}/projects/${projectId}/documents`}><FilePlus2 size={16}/> Open MDR & register documents</Link></div></header>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="MDR deliverables" value={docs.length} icon={<FileStack/>}/><Metric label="Awaiting DCC review" value={awaiting} icon={<ClipboardCheck/>} warn={awaiting>0}/><Metric label="Not submitted" value={unsubmitted} icon={<FileClock/>} warn={unsubmitted>0}/><Metric label="Overdue submissions" value={overdue} icon={<AlertTriangle/>} warn={overdue>0}/><Metric label="Discipline engineers" value={engineers} icon={<UsersRound/>}/></section>
  <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.65fr)]"><div className="space-y-5"><article className="ev-card p-5 sm:p-6"><p className="ev-label">Project brief communicated by management</p><h2 className="mt-2 font-semibold">{project?.name}</h2><p className="mt-3 text-sm leading-7 text-[#617083]">{project?.project_introduction||"Management has not yet recorded the project introduction."}</p><div className="mt-4"><p className="ev-label">Key objectives</p>{project?.key_objectives?.length?<ol className="mt-2 space-y-1.5 text-sm text-[#24384f]">{project.key_objectives.map((objective:string,index:number)=><li className="flex gap-2" key={`${index}-${objective}`}><span className="font-bold text-[#e8733f]">{index+1}.</span><span>{objective}</span></li>)}</ol>:<p className="mt-1 text-sm text-[#617083]">No key objectives have been recorded.</p>}</div>{project?.planned_end_date&&<p className="mt-4 text-xs font-semibold text-[#0c5b45]">Planned project completion: {new Date(`${project.planned_end_date}T00:00:00`).toLocaleDateString()}</p>}</article>
  <article className="ev-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf1ef] px-5 py-4"><div><h2 className="font-semibold">MDR by discipline</h2><p className="mt-1 text-xs text-[#617083]">Use this to confirm that every discipline has a populated delivery plan.</p></div></div><div className="grid gap-px bg-[#edf1ef] sm:grid-cols-2 lg:grid-cols-3">{[...disciplineCounts.entries()].map(([name,count])=><div className="bg-white p-5" key={name}><p className="text-sm font-semibold">{name}</p><p className="mt-2 text-2xl font-semibold text-[#0c5b45]">{count}</p><p className="text-xs text-[#617083]">planned deliverable{count===1?"":"s"}</p></div>)}{!disciplineCounts.size&&<p className="bg-white p-8 text-center text-sm text-[#617083] sm:col-span-2 lg:col-span-3">The MDR is empty. Register the first planned deliverable.</p>}</div></article>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Action href={`/app/${organisationId}/projects/${projectId}/documents`} title="Populate MDR" body="Create deliverable records, disciplines and agreed submission dates."/><Action href={`/app/${organisationId}/projects/${projectId}/reviews`} title="Review submissions" body="Accept compliant engineer revisions or return them with comments."/><Action href={`/app/${organisationId}/projects/${projectId}/work-packages/transmittals/new`} title="Transmit documents" body="Select accepted revisions and issue a controlled client acknowledgement transmittal."/><Action href={`/app/${organisationId}/projects/${projectId}/work-packages`} title="Prepare work packages" body="Freeze approved revisions into organised handover packages."/></div></div><aside className="space-y-5"><ProjectIssueForm organisationId={organisationId} projectId={projectId}/><article className="ev-card p-5"><h2 className="font-semibold">Current control exceptions</h2><p className="mt-3 text-3xl font-semibold text-[#a5452f]">{issueRows?.length??0}</p><p className="mt-1 text-xs leading-5 text-[#617083]">Open project issues are visible to management for oversight and resolution.</p><Link className="ev-button-secondary mt-4" href={`/app/${organisationId}/projects/${projectId}/team`}><UsersRound size={16}/> View discipline engineers</Link></article></aside></section></div>;
}

function Metric({label,value,icon,warn=false}:{label:string;value:number;icon:React.ReactNode;warn?:boolean}){return <article className="ev-card p-5"><span className={warn?"text-[#b6532b]":"text-[#e8733f]"}>{icon}</span><p className={`mt-4 text-2xl font-semibold ${warn?"text-[#a5452f]":""}`}>{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#617083]">{label}</p></article>}
function Action({href,title,body}:{href:string;title:string;body:string}){return <Link href={href} className="ev-card block p-5 transition hover:-translate-y-0.5 hover:border-[#f0b091]"><h3 className="font-semibold text-[#0c5b45]">{title}</h3><p className="mt-2 text-xs leading-5 text-[#617083]">{body}</p></Link>}
