import Link from "next/link";
import {AlertTriangle,Building2,CheckCircle2,CircleUserRound,Clock3,FileWarning,Filter,HeartPulse,KeyRound,RefreshCw,Search,ShieldAlert,UsersRound} from "lucide-react";
import {getFounderDashboard,type FounderOrganisation,type FounderUser} from "@/lib/founder";
import {healthClasses,licenceDurationLabel,licenceTimeLabel} from "@/lib/founder-health";

export const metadata={title:"Founder control centre"};

type SearchParams={q?:string;health?:string};

export default async function FounderPage({searchParams}:{searchParams:Promise<SearchParams>}){
  const requested=await searchParams;
  const q=(requested.q??"").slice(0,100);
  const health=["all","healthy","attention","critical"].includes(requested.health??"")?requested.health!:"all";
  const dashboard=await getFounderDashboard({search:q,health});
  return <main className="mx-auto w-full max-w-[1900px] px-4 py-7 sm:px-6 lg:px-8 lg:py-10">
    <div className="flex flex-wrap items-end justify-between gap-5">
      <div><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.17em] text-[#e36b35]"><HeartPulse size={15}/> Platform oversight</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-[#10243e] sm:text-4xl">Organisation and licence health</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#617083]">A secure operational view of every EngiCite organisation, user account, licence period and risk requiring founder attention.</p></div>
      <div className="flex items-center gap-2 rounded-xl border border-[#dce4ea] bg-white px-3 py-2 text-xs text-[#617083]"><Clock3 size={14}/><span>Updated {formatDateTime(dashboard.generated_at)}</span><Link href="/founder" className="ml-1 grid size-7 place-items-center rounded-lg text-[#10243e] hover:bg-[#eef3f6]" aria-label="Refresh control centre"><RefreshCw size={14}/></Link></div>
    </div>

    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-6" aria-label="Platform summary">
      <SummaryCard icon={<Building2 size={19}/>} label="All organisations" value={dashboard.summary.organisations} note={`${dashboard.summary.new_organisations} new this week`}/>
      <SummaryCard icon={<KeyRound size={19}/>} label="Current licences" value={dashboard.summary.active_licences} note="Pilot or paid access"/>
      <SummaryCard icon={<UsersRound size={19}/>} label="App users" value={dashboard.summary.users} note="All registered accounts"/>
      <SummaryCard icon={<ShieldAlert size={19}/>} label="Need attention" value={dashboard.summary.needs_attention} note="Account or delivery risk" tone={dashboard.summary.needs_attention?"warning":"normal"}/>
      <SummaryCard icon={<CircleUserRound size={19}/>} label="Orphaned users" value={dashboard.summary.orphaned_users} note="No active organisation" tone={dashboard.summary.orphaned_users?"critical":"normal"}/>
      <SummaryCard icon={<CheckCircle2 size={19}/>} label="Healthy tenants" value={Math.max(0,dashboard.summary.organisations-dashboard.summary.needs_attention)} note="No material warning" tone="success"/>
    </section>

    <form className="mt-6 grid gap-3 rounded-2xl border border-[#dbe4ea] bg-white p-4 shadow-[0_8px_30px_rgba(16,36,62,.05)] sm:grid-cols-[minmax(240px,1fr)_220px_auto_auto]">
      <label><span className="ev-label">Search organisations or users</span><span className="relative block"><Search className="absolute left-3 top-3.5 text-[#8795a5]" size={16}/><input name="q" defaultValue={q} className="ev-input pl-9" placeholder="Name, email or organisation slug"/></span></label>
      <label><span className="ev-label">Account health</span><span className="relative block"><Filter className="pointer-events-none absolute left-3 top-3.5 text-[#8795a5]" size={15}/><select name="health" defaultValue={health} className="ev-input pl-9"><option value="all">All health states</option><option value="healthy">Healthy</option><option value="attention">Needs attention</option><option value="critical">Critical</option></select></span></label>
      <button className="ev-button self-end">Apply filters</button>
      {(q||health!=="all")&&<Link href="/founder" className="ev-button-secondary self-end">Clear</Link>}
    </form>

    <section id="organisations" className="mt-8">
      <div className="flex items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#e36b35]">Tenant portfolio</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.03em]">All organisations</h2></div><span className="text-xs text-[#6a7889]">Showing {dashboard.organisations.length} of {dashboard.summary.organisations}</span></div>
      <div className="mt-4 hidden overflow-x-auto rounded-2xl border border-[#dbe4ea] bg-white shadow-[0_10px_34px_rgba(16,36,62,.05)] lg:block"><table className="w-full min-w-[1280px] text-left"><thead><tr className="border-b border-[#e5ebef] bg-[#f8fafb] text-[10px] font-extrabold uppercase tracking-[.13em] text-[#6c7a8b]"><th className="p-4">Organisation</th><th>Health</th><th>Licence</th><th>Period remaining</th><th>Users</th><th>Projects</th><th>Delivery signals</th><th>Last activity</th></tr></thead><tbody>{dashboard.organisations.map(organisation=><OrganisationRow key={organisation.id} organisation={organisation}/>)}</tbody></table>{!dashboard.organisations.length&&<EmptyState text="No organisations match these filters."/>}</div>
      <div className="mt-4 grid gap-4 lg:hidden">{dashboard.organisations.map(organisation=><OrganisationCard key={organisation.id} organisation={organisation}/>)}{!dashboard.organisations.length&&<div className="ev-card"><EmptyState text="No organisations match these filters."/></div>}</div>
    </section>

    <section id="users" className="mt-10">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#e36b35]">Identity directory</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.03em]">Application users</h2><p className="mt-1 text-sm text-[#617083]">Account identity and membership status only. Passwords and authentication secrets are never visible.</p></div><span className="rounded-full border border-[#dce4ea] bg-white px-3 py-1.5 text-xs font-semibold text-[#5e6e80]">Maximum 100 shown</span></div>
      <div className="mt-4 overflow-x-auto rounded-2xl border border-[#dbe4ea] bg-white shadow-[0_10px_34px_rgba(16,36,62,.05)]"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-[#e5ebef] bg-[#f8fafb] text-[10px] font-extrabold uppercase tracking-[.13em] text-[#6c7a8b]"><th className="p-4">User</th><th>Organisation membership</th><th>Project roles</th><th>Account state</th><th>Last sign-in</th><th>Created</th></tr></thead><tbody>{dashboard.users.map(user=><UserRow key={user.id} user={user}/>)}</tbody></table>{!dashboard.users.length&&<EmptyState text="No users match this search."/>}</div>
    </section>

    <footer className="mt-8 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#d8e1e8] bg-[#eaf0f4] p-4 text-xs leading-5 text-[#536478]"><span><strong className="text-[#10243e]">Founder security:</strong> read-only database functions, explicit founder allow-list, authenticator MFA and immutable access auditing.</span><span>No engineering document content is returned here.</span></footer>
  </main>;
}

function SummaryCard({icon,label,value,note,tone="normal"}:{icon:React.ReactNode;label:string;value:number;note:string;tone?:"normal"|"warning"|"critical"|"success"}){
  const style=tone==="critical"?"border-[#efc9c5] bg-[#fff7f6] text-[#a33b35]":tone==="warning"?"border-[#efd9ae] bg-[#fffbef] text-[#86580d]":tone==="success"?"border-[#c8e3d8] bg-[#f5fbf8] text-[#0c684e]":"border-[#dbe4ea] bg-white text-[#10243e]";
  return <article className={`rounded-2xl border p-4 shadow-[0_8px_25px_rgba(16,36,62,.04)] ${style}`}><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-white/80 shadow-sm">{icon}</span><strong className="text-2xl tracking-[-.04em]">{value.toLocaleString()}</strong></div><p className="mt-4 text-[10px] font-extrabold uppercase tracking-[.13em]">{label}</p><p className="mt-1 text-xs opacity-70">{note}</p></article>;
}

function OrganisationRow({organisation:o}:{organisation:FounderOrganisation}){
  return <tr className="border-b border-[#edf1f4] align-top last:border-0"><td className="p-4"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#edf2f6] font-bold text-[#10243e]">{o.name.slice(0,2).toUpperCase()}</span><div><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-[#10243e]">{o.name}</strong>{o.is_new&&<span className="rounded-full bg-[#fff0e8] px-2 py-0.5 text-[9px] font-extrabold uppercase tracking-wider text-[#d95f2a]">New</span>}{o.status!=="active"&&<span className="rounded-full bg-[#f1f3f5] px-2 py-0.5 text-[9px] font-bold uppercase text-[#657386]">{o.status}</span>}</div><p className="mt-1 text-xs text-[#738194]">{o.owner_name??"No active administrator"}</p><p className="mt-0.5 max-w-[210px] truncate text-[11px] text-[#8a97a6]">{o.owner_email??o.slug}</p></div></div></td><td className="py-4 pr-4"><HealthBadge organisation={o}/></td><td className="py-4 pr-4"><strong className="block text-sm text-[#10243e]">{o.plan_name}</strong><span className="mt-1 block text-xs capitalize text-[#6f7d8e]">{o.subscription_status.replaceAll("_"," ")}{o.provider_name?` · ${o.provider_name}`:""}</span>{o.cancel_at_period_end&&<span className="mt-1 block text-[10px] font-bold text-[#a65b28]">Cancels at period end</span>}</td><td className="py-4 pr-4"><strong className={`text-sm ${o.licence_days_remaining!==null&&o.licence_days_remaining<=7?"text-[#a33b35]":"text-[#10243e]"}`}>{licenceTimeLabel(o.licence_days_remaining,o.subscription_status)}</strong><span className="mt-1 block text-xs text-[#758294]">{licenceDurationLabel(o.licence_duration_days)}</span><span className="mt-1 block text-[11px] text-[#8b97a5]">Ends {formatDate(o.licence_ends_at)}</span></td><td className="py-4 pr-4"><strong className="text-sm">{o.active_users}</strong><span className="text-xs text-[#7b8796]"> / {o.total_users} active</span><p className="mt-1 text-[11px] text-[#8b97a5]">{o.pending_invitations} pending invite{o.pending_invitations===1?"":"s"}</p></td><td className="py-4 pr-4"><strong className="text-sm">{o.active_projects}</strong><span className="text-xs text-[#7b8796]"> active</span><p className="mt-1 text-[11px] text-[#8b97a5]">{o.archived_projects} archived</p></td><td className="py-4 pr-4"><p className="text-xs"><strong>{o.total_documents}</strong> MDR records</p><p className={`mt-1 text-xs ${o.overdue_documents?"font-semibold text-[#a55d11]":"text-[#7a8796]"}`}>{o.overdue_documents} overdue</p><p className={`mt-1 text-xs ${o.failed_revisions?"font-semibold text-[#a33b35]":"text-[#7a8796]"}`}>{o.failed_revisions} processing failures</p></td><td className="py-4 pr-4 text-xs text-[#617083]"><span className="block">{formatDateTime(o.last_activity_at)}</span><span className="mt-2 block font-mono text-[10px] text-[#8995a3]">{o.slug}</span></td></tr>;
}

function OrganisationCard({organisation:o}:{organisation:FounderOrganisation}){
  return <article className="ev-card overflow-hidden"><div className="flex items-start justify-between gap-4 border-b border-[#e8edf1] p-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#10243e]">{o.name}</h3>{o.is_new&&<span className="rounded-full bg-[#fff0e8] px-2 py-0.5 text-[9px] font-extrabold uppercase text-[#d95f2a]">New</span>}</div><p className="mt-1 text-xs text-[#738194]">{o.owner_name??"No active administrator"}</p></div><HealthBadge organisation={o}/></div><div className="grid grid-cols-2 gap-px bg-[#e8edf1]"><Metric label="Licence" value={o.plan_name} note={licenceTimeLabel(o.licence_days_remaining,o.subscription_status)}/><Metric label="Users" value={`${o.active_users} active`} note={`${o.total_users} total`}/><Metric label="Projects" value={`${o.active_projects} active`} note={`${o.archived_projects} archived`}/><Metric label="MDR records" value={String(o.total_documents)} note={`${o.overdue_documents} overdue`}/></div>{o.warnings.length>0&&<details className="border-t border-[#e8edf1] p-4"><summary className="cursor-pointer text-xs font-bold text-[#9c5720]">View {o.warnings.length} health warning{o.warnings.length===1?"":"s"}</summary><ul className="mt-3 space-y-2 text-xs text-[#6d5a4d]">{o.warnings.map(warning=><li key={warning} className="flex gap-2"><AlertTriangle size={13} className="mt-0.5 shrink-0"/>{warning}</li>)}</ul></details>}<div className="border-t border-[#e8edf1] px-4 py-3 font-mono text-[10px] text-[#8995a3]">Tenant: {o.slug}</div></article>;
}

function HealthBadge({organisation:o}:{organisation:FounderOrganisation}){return <div><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.08em] ${healthClasses(o.health_state)}`}>{o.health_state==="healthy"?<CheckCircle2 size={12}/>:o.health_state==="attention"?<AlertTriangle size={12}/>:<FileWarning size={12}/>} {o.health_state}</span><p className="mt-1 text-center text-[11px] font-bold text-[#657386]">{o.health_score}/100</p>{o.warnings.length>0&&<details className="relative mt-1"><summary className="cursor-pointer text-[10px] font-semibold text-[#8a6321]">{o.warnings.length} warning{o.warnings.length===1?"":"s"}</summary><div className="absolute left-0 z-20 mt-2 w-64 rounded-xl border border-[#ead8b8] bg-[#fffaf0] p-3 shadow-xl"><ul className="space-y-2 text-xs leading-5 text-[#705a37]">{o.warnings.map(warning=><li key={warning}>• {warning}</li>)}</ul></div></details>}</div>}

function UserRow({user}:{user:FounderUser}){return <tr className="border-b border-[#edf1f4] align-top last:border-0"><td className="p-4"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#10243e] text-xs font-bold text-white">{user.display_name.slice(0,1).toUpperCase()}</span><div><strong className="text-sm text-[#10243e]">{user.display_name}</strong><p className="mt-0.5 max-w-[240px] truncate text-xs text-[#6f7d8d]">{user.email??"Email removed"}</p></div></div></td><td className="py-4 pr-4">{user.organisations.length?<div className="space-y-1">{user.organisations.slice(0,3).map(org=><p key={org.organisation_id} className="text-xs"><strong>{org.organisation_name}</strong><span className="ml-1 text-[#778494]">· {org.role.replaceAll("_"," ")} · {org.status}</span></p>)}</div>:<span className="text-xs font-semibold text-[#a33b35]">No organisation</span>}</td><td className="py-4 pr-4"><div className="flex max-w-[220px] flex-wrap gap-1">{user.project_roles.length?user.project_roles.map(role=><span key={role} className="rounded-full bg-[#edf2f6] px-2 py-1 text-[10px] font-semibold text-[#4f6175]">{role.replaceAll("_"," ")}</span>):<span className="text-xs text-[#8b97a4]">No project role</span>}</div></td><td className="py-4 pr-4"><AccountState state={user.account_state}/>{!user.email_confirmed_at&&<p className="mt-1 text-[10px] text-[#9a6324]">Email unverified</p>}</td><td className="py-4 pr-4 text-xs text-[#617083]">{formatDateTime(user.last_sign_in_at)}</td><td className="py-4 pr-4 text-xs text-[#617083]">{formatDate(user.created_at)}</td></tr>}

function AccountState({state}:{state:FounderUser["account_state"]}){const style=state==="active"?"bg-[#edf8f4] text-[#0c684e]":state==="suspended"||state==="orphaned"?"bg-[#fff0ef] text-[#a33b35]":"bg-[#fff7e8] text-[#8b5a0a]";return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.07em] ${style}`}>{state.replaceAll("_"," ")}</span>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="bg-white p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#788597]">{label}</p><strong className="mt-1 block text-sm text-[#10243e]">{value}</strong><p className="mt-1 text-xs text-[#7a8796]">{note}</p></div>}
function EmptyState({text}:{text:string}){return <div className="p-10 text-center text-sm text-[#718093]">{text}</div>}
function formatDate(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(value))}
function formatDateTime(value:string|null){if(!value)return "Never";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"UTC"}).format(new Date(value))}
