"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireUser, requireProject } from "@/lib/auth";

const slug=z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).min(3).max(48);
export type MutationState={message?:string}|undefined;
export async function createOrganisation(_:MutationState,form:FormData):Promise<MutationState>{const parsed=z.object({name:z.string().trim().min(2).max(100),slug}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter a valid organisation name and lowercase URL slug."};const {supabase}=await requireUser();const {data,error}=await supabase.rpc("create_organisation",parsed.data);if(error?.code==="23505"){const {data:recovered,error:recoveryError}=await supabase.rpc("recover_created_organisation",{organisation_slug:parsed.data.slug});if(!recoveryError&&recovered)redirect(`/app/${recovered}`);return {message:"This organisation slug already exists and could not be reclaimed by the signed-in account."};}if(error)return {message:`Organisation could not be created: ${error.message} Reference: ${error.code}.`};redirect(`/app/${data}`)}
export async function createProject(_:MutationState,form:FormData):Promise<MutationState>{const parsed=z.object({organisationId:z.uuid(),code:z.string().trim().toUpperCase().regex(/^[A-Z0-9][A-Z0-9-]{1,19}$/),name:z.string().trim().min(2).max(120)}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter a valid project code and project name."};const {supabase}=await requireUser();const {error}=await supabase.from("projects").insert({organisation_id:parsed.data.organisationId,code:parsed.data.code,name:parsed.data.name});if(error)return {message:`Project could not be created: ${error.message} Reference: ${error.code}.`};revalidatePath(`/app/${parsed.data.organisationId}`);return {message:"Project created successfully."};}
export async function createDocument(_:MutationState,form:FormData):Promise<MutationState>{const optional=z.preprocess(v=>typeof v==="string"&&v.trim()===""?null:v,z.string().trim().max(80).nullable());const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),documentNumber:z.string().trim().toUpperCase().min(2).max(80),title:z.string().trim().min(2).max(240),documentType:z.string().trim().min(2).max(80),discipline:z.string().trim().min(2).max(80),area:optional,system:optional,workPackage:optional}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter valid document metadata in every required field."};const {supabase}=await requireProject(parsed.data.organisationId,parsed.data.projectId);const {data,error}=await supabase.from("documents").insert({organisation_id:parsed.data.organisationId,project_id:parsed.data.projectId,document_number:parsed.data.documentNumber,title:parsed.data.title,document_type:parsed.data.documentType,discipline:parsed.data.discipline,area:parsed.data.area,system:parsed.data.system,work_package:parsed.data.workPackage}).select("id").single();if(error)return {message:error.code==="23505"?"That document number already exists in this project.":`Document could not be created. Reference: ${error.code}.`};redirect(`/app/${parsed.data.organisationId}/projects/${parsed.data.projectId}/documents/${data.id}`)}

export async function createDocumentCategory(_:MutationState,form:FormData):Promise<MutationState>{const parsed=z.object({organisationId:z.uuid(),kind:z.enum(["discipline","document_type"]),code:z.string().trim().toUpperCase().regex(/^[A-Z0-9-]{1,24}$/),name:z.string().trim().min(2).max(80)}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter a category name and a short code using letters, numbers or hyphens."};const {supabase}=await requireUser();const {error}=await supabase.from("document_categories").insert({organisation_id:parsed.data.organisationId,kind:parsed.data.kind,code:parsed.data.code,name:parsed.data.name});if(error)return {message:error.code==="23505"?"That category code already exists.":`Category could not be created. Reference: ${error.code}.`};revalidatePath(`/app/${parsed.data.organisationId}/settings/document-categories`);return {message:"Category added."}}

export async function toggleDocumentCategory(form:FormData){const parsed=z.object({organisationId:z.uuid(),categoryId:z.uuid(),isActive:z.enum(["true","false"])}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const {supabase}=await requireUser();await supabase.from("document_categories").update({is_active:parsed.data.isActive==="true"}).eq("organisation_id",parsed.data.organisationId).eq("id",parsed.data.categoryId);revalidatePath(`/app/${parsed.data.organisationId}/settings/document-categories`)}

export async function updateOrganisation(_:MutationState,form:FormData):Promise<MutationState>{const parsed=z.object({organisationId:z.uuid(),name:z.string().trim().min(2).max(100)}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter a valid organisation name."};const {supabase}=await requireUser();const {error}=await supabase.rpc("update_organisation",{target_organisation:parsed.data.organisationId,new_name:parsed.data.name});if(error)return {message:`Organisation could not be updated. Reference: ${error.code}.`};revalidatePath(`/app/${parsed.data.organisationId}`);return {message:"Organisation updated."}}
export async function setOrganisationArchived(form:FormData){const parsed=z.object({organisationId:z.uuid(),archived:z.enum(["true","false"])}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const {supabase}=await requireUser();await supabase.rpc("set_organisation_archived",{target_organisation:parsed.data.organisationId,archived:parsed.data.archived==="true"});redirect("/app")}
export async function updateProject(_:MutationState,form:FormData):Promise<MutationState>{const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),code:z.string().trim().toUpperCase().regex(/^[A-Z0-9][A-Z0-9-]{1,19}$/),name:z.string().trim().min(2).max(120),description:z.string().trim().max(1000)}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter valid project details."};const {supabase}=await requireUser();const {error}=await supabase.rpc("update_project",{target_organisation:parsed.data.organisationId,target_project:parsed.data.projectId,new_code:parsed.data.code,new_name:parsed.data.name,new_description:parsed.data.description});if(error)return {message:`Project could not be updated. Reference: ${error.code}.`};revalidatePath(`/app/${parsed.data.organisationId}`);return {message:"Project updated."}}
export async function setProjectArchived(form:FormData){const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),archived:z.enum(["true","false"])}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const {supabase}=await requireUser();await supabase.rpc("set_project_archived",{target_organisation:parsed.data.organisationId,target_project:parsed.data.projectId,archived:parsed.data.archived==="true"});redirect(`/app/${parsed.data.organisationId}`)}
export async function updateDocument(_:MutationState,form:FormData):Promise<MutationState>{const optional=z.string().trim().max(80);const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),documentId:z.uuid(),documentNumber:z.string().trim().toUpperCase().min(2).max(80),title:z.string().trim().min(2).max(240),documentType:z.string().trim().min(2).max(80),discipline:z.string().trim().min(2).max(80),area:optional,system:optional,workPackage:optional}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter valid document metadata."};const {supabase}=await requireProject(parsed.data.organisationId,parsed.data.projectId);const {error}=await supabase.rpc("update_document",{target_organisation:parsed.data.organisationId,target_project:parsed.data.projectId,target_document:parsed.data.documentId,new_number:parsed.data.documentNumber,new_title:parsed.data.title,new_type:parsed.data.documentType,new_discipline:parsed.data.discipline,new_area:parsed.data.area,new_system:parsed.data.system,new_work_package:parsed.data.workPackage});if(error)return {message:`Document could not be updated. Reference: ${error.code}.`};revalidatePath(`/app/${parsed.data.organisationId}/projects/${parsed.data.projectId}/documents/${parsed.data.documentId}`);return {message:"Document metadata updated."}}
export async function setDocumentArchived(form:FormData){const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),documentId:z.uuid(),archived:z.enum(["true","false"])}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const {supabase}=await requireProject(parsed.data.organisationId,parsed.data.projectId);await supabase.rpc("set_document_archived",{target_organisation:parsed.data.organisationId,target_project:parsed.data.projectId,target_document:parsed.data.documentId,archived:parsed.data.archived==="true"});redirect(`/app/${parsed.data.organisationId}/projects/${parsed.data.projectId}/documents`)}
export async function createWorkPackage(_:MutationState,form:FormData):Promise<MutationState>{const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),packageNumber:z.string().trim().toUpperCase().min(2).max(80),name:z.string().trim().min(2).max(160),purpose:z.string().trim().max(1000),discipline:z.string().trim().max(80),requiredStatus:z.string().trim().max(80),destination:z.enum(["local","sharepoint","google_drive"])}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter valid package details."};const {supabase}=await requireProject(parsed.data.organisationId,parsed.data.projectId);const {data,error}=await supabase.rpc("create_frozen_work_package",{target_organisation:parsed.data.organisationId,target_project:parsed.data.projectId,new_number:parsed.data.packageNumber,new_name:parsed.data.name,new_purpose:parsed.data.purpose,filter_discipline:parsed.data.discipline,required_status:parsed.data.requiredStatus,target_destination:parsed.data.destination});if(error)return {message:error.code==="23505"?"That package number and version already exist.":`Package could not be created. Reference: ${error.code}.`};redirect(`/app/${parsed.data.organisationId}/projects/${parsed.data.projectId}/work-packages/${data}`)}
export async function updateDocumentPlan(_:MutationState,form:FormData):Promise<MutationState>{const date=z.preprocess(v=>v===""?null:v,z.iso.date().nullable());const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),documentId:z.uuid(),responsibleParty:z.string().trim().max(80),plannedSubmissionDate:date,plannedFinalDate:date,requiredIssueStatus:z.string().trim().max(80),progressWeight:z.coerce.number().positive().max(1000)}).safeParse(Object.fromEntries(form));if(!parsed.success)return {message:"Enter valid planning dates and a positive progress weight."};const {supabase}=await requireProject(parsed.data.organisationId,parsed.data.projectId);const {error}=await supabase.rpc("update_document_plan",{target_organisation:parsed.data.organisationId,target_project:parsed.data.projectId,target_document:parsed.data.documentId,new_responsible:parsed.data.responsibleParty,new_submission:parsed.data.plannedSubmissionDate,new_final:parsed.data.plannedFinalDate,new_required_status:parsed.data.requiredIssueStatus,new_weight:parsed.data.progressWeight});if(error)return {message:`Document plan could not be updated. Reference: ${error.code}.`};revalidatePath(`/app/${parsed.data.organisationId}/projects/${parsed.data.projectId}/progress`);return {message:"Document plan updated."}}
