"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireUser, requireProject } from "@/lib/auth";

const slug=z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).min(3).max(48);
export async function createOrganisation(form:FormData){const parsed=z.object({name:z.string().trim().min(2).max(100),slug}).safeParse(Object.fromEntries(form));if(!parsed.success)throw new Error("Invalid organisation details.");const {supabase}=await requireUser();const {data,error}=await supabase.rpc("create_organisation",parsed.data);if(error)throw new Error("Organisation could not be created.");redirect(`/app/${data}`)}
export async function createProject(form:FormData){const parsed=z.object({organisationId:z.uuid(),code:z.string().trim().toUpperCase().regex(/^[A-Z0-9][A-Z0-9-]{1,19}$/),name:z.string().trim().min(2).max(120)}).safeParse(Object.fromEntries(form));if(!parsed.success)throw new Error("Invalid project details.");const {supabase}=await requireUser();const {error}=await supabase.from("projects").insert({organisation_id:parsed.data.organisationId,code:parsed.data.code,name:parsed.data.name});if(error)throw new Error("Project could not be created.");revalidatePath("/app");}
export async function createDocument(form:FormData){const parsed=z.object({organisationId:z.uuid(),projectId:z.uuid(),documentNumber:z.string().trim().toUpperCase().min(2).max(80),title:z.string().trim().min(2).max(240),documentType:z.string().trim().min(2).max(60),discipline:z.string().trim().min(2).max(60)}).safeParse(Object.fromEntries(form));if(!parsed.success)throw new Error("Invalid document metadata.");const {supabase}=await requireProject(parsed.data.organisationId,parsed.data.projectId);const {error}=await supabase.from("documents").insert({organisation_id:parsed.data.organisationId,project_id:parsed.data.projectId,document_number:parsed.data.documentNumber,title:parsed.data.title,document_type:parsed.data.documentType,discipline:parsed.data.discipline});if(error)throw new Error("Document could not be created.");revalidatePath(`/app/${parsed.data.organisationId}/projects/${parsed.data.projectId}/documents`)}
