import Link from "next/link";
import {redirect} from "next/navigation";
import {AlertTriangle,ArrowLeft,CheckCircle2,Clock3,FileText,FolderKanban,HeartPulse,Settings,UsersRound} from "lucide-react";
import {requireProject} from "@/lib/auth";
import {projectHomePath,roleLabel,workspacePersona} from "@/lib/role-experience";
import {assessProjectHealth,healthTone} from "@/lib/project-health";
import {EditableProjectBrief,ProjectIssueForm,ResourcePlanForm} from "@/components/project-management-forms";
import {ProjectInviteDialog} from "@/components/project-invite-dialog";
import {setProjectIssueStatus} from "@/app/app/workflow-actions";
import {ProjectLogo} from "@/components/project-logo";

type Progress={progress_weight:number;progress_credit:number;overdue:boolean;uploaded:boolean};
type Issue={id:string;title:string;description:string|null;severity:string;status:string;owner_name:string|null;due_date:string|null;created_at:string};
type Resource={id:string;discipline:string;required_count:number;notes:string|null};
type Member={user_id:string;display_name:string;email:string;role:string;disciplines:string[]};
type Discipline={code:string;name:string};

export default async function ProjectOverview({params}:{params:Promise<{organisationId:string;projectId:string}>}){
  const {organisationId,projectId}=await params;const {supabase,access}=await requireProject(organisationId,projectId);const role=String(access.role);
  if(workspacePersona(role)!=="management")redirect(projectHomePath(organisationId,projectId,role));
  const [{data:project},{data:progressRows},{data:issueRows},{data:resourceRows},{data:teamRows},{data:categoryRows}]=await Promise.all([
    supabase.from("projects").select("id,organisation_id,code,name,description,project_introduction,key_objectives,planned_start_date,planned_end_date").eq("organisation_id",organisationId).eq("id",projectId).single(),
    supabase.from("project_document_progress").select("progress_weight,progress_credit,overdue,uploaded").eq("organisation_id",organisationId).eq("project_id",projectId).eq("lifecycle_status","active"),
    supabase.from("project_issues").select("id,title,description,severity,status,owner_name,due_date,created_at").eq("organisation_id",organisationId).eq("project_id",projectId).order("status").order("created_at",{ascending:false}),
    supabase.from("project_resource_plans").select("id,discipline,required_count,notes").eq("organisation_id",organisationId).eq("project_id",projectId).order("discipline"),
    supabase.rpc("get_project_team",{target_organisation:organisationId,target_project:projectId}),
    supabase.from("document_categories").select("code,name").eq("organisation_id",organisationId).eq("kind","discipline").eq("is_active",true).order("sort_order")
  ]);
  const progress=(progressRows??[]) as Progress[];const issues=(issueRows??[]) as Issue[];const resources=(resourceRows??[]) as Resource[];const members=(teamRows??[]) as Member[];const disciplines=(categoryRows??[]) as Discipline[];
  const totalWeight=progress.reduce((sum,row)=>sum+Number(row.progress_weight),0);const completion=totalWeight?Math.round(progress.reduce((sum,row)=>sum+Number(row.progress_weight)*row.progress_credit/100,0)/totalWeight*100):0;const overdue=progress.filter(row=>row.overdue).length;const openIssues=issues.filter(issue=>issue.status!=="resolved");const critical=openIssues.filter(issue=>issue.severity==="critical").length;const high=openIssues.filter(issue=>issue.severity==="high").length;const health=assessProjectHealth({deliverables:progress.length,completion,overdue,highIssues:high,criticalIssues:critical});const dccCount=members.filter(member=>member.role==="document_controller").length;const engineerCount=members.filter(member=>member.role==="engineer").length;
  return <div className="mx-auto max-w-[1500px]"><Link href={`/app/${organisationId}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#0c5b45]"><ArrowLeft size={16}/> Portfolio oversight</Link><header className="mt-6 flex flex-wrap items-end justify-between gap-4"><div className="flex items-start gap-4"><span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl border border-[#dfe7e3] bg-white p-2 text-[#e8733f] shadow-sm"><ProjectLogo organisationId={organisationId} projectId={projectId} name={project?.name??"Project"} size={64} className="size-full object-contain"/></span><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8733f]">Management workspace · {roleLabel(role)}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{project?.code} · {project?.name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#617083]">Monitor project health, progress, resources and issues. Operational MDR and engineer submission controls are intentionally kept in their own workspaces.</p></div></div><div className="flex flex-wrap gap-2"><Link className="ev-button" href={`/app/${organisationId}/projects/${projectId}/reports`}><FileText size={16}/> Project report</Link><ProjectInviteDialog organisationId={organisationId} projectId={projectId} disciplines={disciplines}/><Link className="ev-button-secondary" href={`/app/${organisationId}/projects/${projectId}/team`}><UsersRound size={16}/> Team & resources</Link><Link className="ev-button-secondary" href={`/app/${organisationId}/projects/${projectId}/settings`}><Settings size={16}/> Project settings</Link></div></header>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Project health" value={health} icon={<HeartPulse/>} tone={healthTone(health)}/><Metric label="Overall progress" value={`${completion}%`} icon={<Clock3/>}/><Metric label="MDR deliverables" value={progress.length} icon={<FolderKanban/>}/><Metric label="Overdue" value={overdue} icon={<AlertTriangle/>} warn={overdue>0}/><Metric label="Open issues" value={openIssues.length} icon={<AlertTriangle/>} warn={critical+high>0}/><Metric label="Project resources" value={`${engineerCount} engineers`} icon={<UsersRound/>}/></section>
  <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.65fr)]"><div className="space-y-5"><EditableProjectBrief organisationId={organisationId} projectId={projectId} introduction={project?.project_introduction||project?.description||""} objectives={project?.key_objectives??[]} startDate={project?.planned_start_date??""} endDate={project?.planned_end_date??""} dccCount={dccCount}/>
  <article className="ev-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf1ef] px-5 py-4"><div><h2 className="font-semibold">Project issues</h2><p className="mt-1 text-xs text-[#617083]">Critical constraints and actions requiring management attention.</p></div><span className="rounded-full bg-[#fff0e9] px-3 py-1 text-xs font-bold text-[#a5452f]">{openIssues.length} open</span></div><div>{issues.length?issues.map(issue=><div className="border-b border-[#edf1ef] p-5 last:border-0" key={issue.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${severityTone(issue.severity)}`}>{issue.severity}</span><span className="text-xs font-semibold capitalize text-[#617083]">{issue.status}</span></div><h3 className="mt-2 font-semibold">{issue.title}</h3>{issue.description&&<p className="mt-2 text-sm leading-6 text-[#617083]">{issue.description}</p>}<p className="mt-2 text-xs text-[#617083]">Owner: {issue.owner_name||"Unassigned"} · Due: {formatDate(issue.due_date)}</p></div>{issue.status!=="resolved"&&<form action={setProjectIssueStatus}><Hidden organisationId={organisationId} projectId={projectId}/><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="status" value="resolved"/><button className="ev-button-secondary whitespace-nowrap"><CheckCircle2 size={15}/> Resolve</button></form>}</div></div>):<p className="p-8 text-center text-sm text-[#617083]">No project issues have been reported.</p>}</div></article>
  <article className="ev-card overflow-hidden"><div className="border-b border-[#edf1ef] px-5 py-4"><h2 className="font-semibold">Discipline resource readiness</h2><p className="mt-1 text-xs text-[#617083]">Required engineers compared with accepted, active discipline assignments.</p></div><div className="grid gap-px bg-[#edf1ef] md:grid-cols-2">{resources.length?resources.map(resource=>{const assigned=members.filter(member=>member.role==="engineer"&&(member.disciplines??[]).some(value=>value.toLowerCase()===resource.discipline.toLowerCase())).length;const gap=Math.max(0,resource.required_count-assigned);return <div className="bg-white p-5" key={resource.id}><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{resource.discipline}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${gap?"bg-[#fff0e9] text-[#a5452f]":"bg-[#e8f1ed] text-[#0c5b45]"}`}>{gap?`${gap} vacancy${gap===1?"":"ies"}`:"Resourced"}</span></div><p className="mt-3 text-2xl font-semibold">{assigned}<span className="text-sm font-normal text-[#617083]"> / {resource.required_count} assigned</span></p>{resource.notes&&<p className="mt-2 text-xs leading-5 text-[#617083]">{resource.notes}</p>}</div>}):<p className="bg-white p-8 text-center text-sm text-[#617083] md:col-span-2">No discipline resource requirements have been set.</p>}</div></article></div>
  <aside className="space-y-5"><ResourcePlanForm organisationId={organisationId} projectId={projectId} disciplines={disciplines}/><ProjectIssueForm organisationId={organisationId} projectId={projectId}/></aside></section></div>;
}

function Metric({label,value,icon,tone="bg-white text-[#10243e]",warn=false}:{label:string;value:string|number;icon:React.ReactNode;tone?:string;warn?:boolean}){return <article className={`ev-card p-5 ${tone}`}><span className={warn?"text-[#b6532b]":"text-[#e8733f]"}>{icon}</span><p className="mt-4 truncate text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] opacity-65">{label}</p></article>}
function Hidden({organisationId,projectId}:{organisationId:string;projectId:string}){return <><input type="hidden" name="organisationId" value={organisationId}/><input type="hidden" name="projectId" value={projectId}/></>}
function formatDate(value:string|null|undefined){return value?new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"Not planned"}
function severityTone(value:string){if(value==="critical")return "bg-[#fde8e4] text-[#9b2c24]";if(value==="high")return "bg-[#fff0e9] text-[#a5452f]";if(value==="medium")return "bg-[#fff7dd] text-[#7a5a00]";return "bg-[#eef1f4] text-[#617083]"}
