import Link from "next/link";
import {AlertTriangle,ArrowLeft,ChevronDown,Clock3,FileText,FolderKanban,KeyRound,ShieldCheck,UsersRound} from "lucide-react";
import {getFounderOrganisationDetail,type FounderUser} from "@/lib/founder";
import {healthClasses,licenceDurationLabel,licenceTimeLabel} from "@/lib/founder-health";

export const metadata={title:"Organisation account oversight"};

export default async function FounderOrganisationPage({params}:{params:Promise<{organisationId:string}>}){
  const {organisationId}=await params;
  const detail=await getFounderOrganisationDetail(organisationId);
  const organisation=detail.organisation!;
  const backHref=organisation.status==="deleted"?"/founder/deleted":"/founder";
  return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-11">
    <Link href={backHref} className="inline-flex items-center gap-2 text-sm font-bold text-[#0c684e]"><ArrowLeft size={16}/> {organisation.status==="deleted"?"Deleted accounts":"Organisation portfolio"}</Link>
    <section className="ev-card mt-6 overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-5 border-b border-[#e3e9ee] p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-[#10243e] text-lg font-bold text-white">{organisation.name.slice(0,2).toUpperCase()}</span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-.035em] text-[#10243e] sm:text-3xl">{organisation.name}</h1>{organisation.is_new&&<span className="rounded-full bg-[#fff0e8] px-2.5 py-1 text-[10px] font-extrabold uppercase text-[#d95f2a]">New</span>}{organisation.status!=="active"&&<span className="rounded-full bg-[#f5e9e7] px-2.5 py-1 text-[10px] font-extrabold uppercase text-[#9c453a]">{organisation.status}</span>}</div><p className="mt-2 text-sm text-[#617083]">{organisation.owner_name??"No active administrator"} · {organisation.owner_email??"Identity removed"}</p><p className="mt-1 font-mono text-[10px] text-[#8a96a4]">{organisation.slug}</p></div></div><span className={`rounded-full border px-3 py-1.5 text-xs font-extrabold uppercase tracking-[.08em] ${healthClasses(organisation.health_state)}`}>{organisation.health_state} · {organisation.health_score}/100</span></div>
      <div className="grid gap-px bg-[#e6ebef] sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<KeyRound size={17}/>} label="Licence" value={organisation.plan_name} note={`${licenceDurationLabel(organisation.licence_duration_days)} · ${licenceTimeLabel(organisation.licence_days_remaining,organisation.subscription_status)}`}/><Metric icon={<UsersRound size={17}/>} label="Users" value={`${organisation.active_users} active`} note={`${organisation.total_users} account memberships`}/><Metric icon={<FolderKanban size={17}/>} label="Projects" value={`${organisation.active_projects} active`} note={`${organisation.archived_projects} archived`}/><Metric icon={<FileText size={17}/>} label="MDR records" value={String(organisation.total_documents)} note={`${organisation.overdue_documents} overdue`}/><Metric icon={<Clock3 size={17}/>} label="Last activity" value={formatDateTime(organisation.last_activity_at)} note={`${organisation.failed_revisions} processing failures`}/></div>
    </section>
    {organisation.warnings.length>0&&<section className="mt-5 rounded-2xl border border-[#efd8ad] bg-[#fffbf0] p-5"><h2 className="flex items-center gap-2 text-sm font-bold text-[#805612]"><AlertTriangle size={17}/> Account-health attention</h2><ul className="mt-3 grid gap-2 text-sm text-[#725f3f] md:grid-cols-2">{organisation.warnings.map(warning=><li key={warning}>• {warning}</li>)}</ul></section>}
    <details className="group ev-card mt-6 overflow-hidden">
      <summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf1f5] text-[#10243e]"><UsersRound size={19}/></span><div><h2 className="font-semibold text-[#10243e]">Organisation identity directory</h2><p className="mt-1 text-xs text-[#6c7a8b]">Collapsed by default · {detail.users.length} account{detail.users.length===1?"":"s"} loaded for this organisation only</p></div></div><ChevronDown className="text-[#66768a] transition group-open:rotate-180" size={19}/></summary>
      <div className="border-t border-[#e4e9ee]"><div className="bg-[#f8fafb] px-5 py-3 text-xs text-[#66768a]"><ShieldCheck size={14} className="mr-1.5 inline text-[#0c684e]"/>Passwords, authentication secrets and document contents are never included.</div><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="border-y border-[#e7ecef] bg-white text-[10px] font-extrabold uppercase tracking-[.12em] text-[#6d7b8b]"><th className="p-4">User</th><th>Organisation role</th><th>Project roles</th><th>Account state</th><th>Last sign-in</th><th>Created</th></tr></thead><tbody>{detail.users.map(user=><UserRow key={user.id} user={user}/>)}</tbody></table>{!detail.users.length&&<p className="p-10 text-center text-sm text-[#718093]">No retained identity memberships for this organisation.</p>}</div></div>
    </details>
  </main>;
}

function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <div className="bg-white p-5"><div className="flex items-center gap-2 text-[#6e7c8d]">{icon}<span className="text-[10px] font-extrabold uppercase tracking-[.12em]">{label}</span></div><strong className="mt-3 block text-lg text-[#10243e]">{value}</strong><p className="mt-1 text-xs text-[#798696]">{note}</p></div>}
function UserRow({user}:{user:FounderUser}){return <tr className="border-b border-[#edf1f4] last:border-0"><td className="p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#10243e] text-xs font-bold text-white">{user.display_name.slice(0,1).toUpperCase()}</span><div><strong className="text-sm text-[#10243e]">{user.display_name}</strong><p className="mt-0.5 max-w-[240px] truncate text-xs text-[#6f7d8d]">{user.email??"Email removed"}</p></div></div></td><td className="text-xs capitalize text-[#526276]">{user.organisation_role.replaceAll("_"," ")} · {user.membership_status}</td><td><div className="flex max-w-[220px] flex-wrap gap-1">{user.project_roles.length?user.project_roles.map(role=><span key={role} className="rounded-full bg-[#edf2f6] px-2 py-1 text-[10px] font-semibold capitalize text-[#4f6175]">{role.replaceAll("_"," ")}</span>):<span className="text-xs text-[#8995a2]">No project role</span>}</div></td><td><AccountState state={user.account_state}/></td><td className="text-xs text-[#617083]">{formatDateTime(user.last_sign_in_at)}</td><td className="text-xs text-[#617083]">{formatDate(user.created_at)}</td></tr>}
function AccountState({state}:{state:FounderUser["account_state"]}){const style=state==="active"?"bg-[#edf8f4] text-[#0c684e]":state==="suspended"?"bg-[#fff0ef] text-[#a33b35]":"bg-[#fff7e8] text-[#8b5a0a]";return <span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.06em] ${style}`}>{state.replaceAll("_"," ")}</span>}
function formatDate(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(value))}
function formatDateTime(value:string|null){if(!value)return "Never";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"UTC"}).format(new Date(value))}
